//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 10:59:28 AM CEST 
//


package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DeviceId" type="{http://www.opensmartgridplatform.org/schemas/security/secretmanagement/2020/05}DeviceIdentification"/&gt;
 *         &lt;element name="SecretTypes" type="{http://www.opensmartgridplatform.org/schemas/security/secretmanagement/2020/05}SecretTypes"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deviceId",
    "secretTypes"
})
@XmlRootElement(name = "getSecretsRequest")
public class GetSecretsRequest {

    @XmlElement(name = "DeviceId", required = true)
    protected String deviceId;
    @XmlElement(name = "SecretTypes", required = true)
    protected SecretTypes secretTypes;

    /**
     * Gets the value of the deviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }

    /**
     * Gets the value of the secretTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SecretTypes }
     *     
     */
    public SecretTypes getSecretTypes() {
        return secretTypes;
    }

    /**
     * Sets the value of the secretTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecretTypes }
     *     
     */
    public void setSecretTypes(SecretTypes value) {
        this.secretTypes = value;
    }

}
