//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 10:59:28 AM CEST 
//


package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opensmartgridplatform.schemas.security.secretmanagement._2020._05 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opensmartgridplatform.schemas.security.secretmanagement._2020._05
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TechnicalFault }
     * 
     */
    public TechnicalFault createTechnicalFault() {
        return new TechnicalFault();
    }

    /**
     * Create an instance of {@link GetSecretsRequest }
     * 
     */
    public GetSecretsRequest createGetSecretsRequest() {
        return new GetSecretsRequest();
    }

    /**
     * Create an instance of {@link SecretTypes }
     * 
     */
    public SecretTypes createSecretTypes() {
        return new SecretTypes();
    }

    /**
     * Create an instance of {@link GetSecretsResponse }
     * 
     */
    public GetSecretsResponse createGetSecretsResponse() {
        return new GetSecretsResponse();
    }

    /**
     * Create an instance of {@link TypedSecrets }
     * 
     */
    public TypedSecrets createTypedSecrets() {
        return new TypedSecrets();
    }

    /**
     * Create an instance of {@link StoreSecretsRequest }
     * 
     */
    public StoreSecretsRequest createStoreSecretsRequest() {
        return new StoreSecretsRequest();
    }

    /**
     * Create an instance of {@link StoreSecretsResponse }
     * 
     */
    public StoreSecretsResponse createStoreSecretsResponse() {
        return new StoreSecretsResponse();
    }

    /**
     * Create an instance of {@link TypedSecret }
     * 
     */
    public TypedSecret createTypedSecret() {
        return new TypedSecret();
    }

}
