//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 10:59:28 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opensmartgridplatform.org/schemas/security/secretmanagement/2020/05", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;
