//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 06:22:35 PM CEST 
//


package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecretType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecretType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="E_METER_MASTER_KEY"/&gt;
 *     &lt;enumeration value="E_METER_AUTHENTICATION_KEY"/&gt;
 *     &lt;enumeration value="E_METER_ENCRYPTION_KEY_UNICAST"/&gt;
 *     &lt;enumeration value="E_METER_ENCRYPTION_KEY_BROADCAST"/&gt;
 *     &lt;enumeration value="G_METER_MASTER_KEY"/&gt;
 *     &lt;enumeration value="G_METER_ENCRYPTION_KEY"/&gt;
 *     &lt;enumeration value="G_METER_FIRMWARE_UPDATE_AUTHENTICATION_KEY"/&gt;
 *     &lt;enumeration value="G_METER_OPTICAL_PORT_KEY"/&gt;
 *     &lt;enumeration value="PPP_PASSWORD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SecretType")
@XmlEnum
public enum SecretType {

    E_METER_MASTER_KEY,
    E_METER_AUTHENTICATION_KEY,
    E_METER_ENCRYPTION_KEY_UNICAST,
    E_METER_ENCRYPTION_KEY_BROADCAST,
    G_METER_MASTER_KEY,
    G_METER_ENCRYPTION_KEY,
    G_METER_FIRMWARE_UPDATE_AUTHENTICATION_KEY,
    G_METER_OPTICAL_PORT_KEY,
    PPP_PASSWORD;

    public String value() {
        return name();
    }

    public static SecretType fromValue(String v) {
        return valueOf(v);
    }

}
