//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 06:22:35 PM CEST 
//


package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DeviceId" type="{http://www.opensmartgridplatform.org/schemas/security/secretmanagement/2020/05}DeviceIdentification"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="TypedSecrets" type="{http://www.opensmartgridplatform.org/schemas/security/secretmanagement/2020/05}TypedSecrets"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deviceId",
    "typedSecrets"
})
@XmlRootElement(name = "storeSecretsRequest")
public class StoreSecretsRequest {

    @XmlElement(name = "DeviceId", required = true)
    protected String deviceId;
    @XmlElement(name = "TypedSecrets", required = true)
    protected TypedSecrets typedSecrets;

    /**
     * Gets the value of the deviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }

    /**
     * Gets the value of the typedSecrets property.
     * 
     * @return
     *     possible object is
     *     {@link TypedSecrets }
     *     
     */
    public TypedSecrets getTypedSecrets() {
        return typedSecrets;
    }

    /**
     * Sets the value of the typedSecrets property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypedSecrets }
     *     
     */
    public void setTypedSecrets(TypedSecrets value) {
        this.typedSecrets = value;
    }

}
