//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 06:22:35 PM CEST 
//


package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Result" type="{http://www.opensmartgridplatform.org/schemas/security/secretmanagement/2020/05}OsgpResultType"/&gt;
 *         &lt;element name="TechnicalFault" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result",
    "technicalFault"
})
@XmlRootElement(name = "storeSecretsResponse")
public class StoreSecretsResponse {

    @XmlElement(name = "Result", required = true)
    @XmlSchemaType(name = "string")
    protected OsgpResultType result;
    @XmlElement(name = "TechnicalFault", required = true)
    protected Object technicalFault;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link OsgpResultType }
     *     
     */
    public OsgpResultType getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsgpResultType }
     *     
     */
    public void setResult(OsgpResultType value) {
        this.result = value;
    }

    /**
     * Gets the value of the technicalFault property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTechnicalFault() {
        return technicalFault;
    }

    /**
     * Sets the value of the technicalFault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTechnicalFault(Object value) {
        this.technicalFault = value;
    }

}
