//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 06:22:35 PM CEST 
//


package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Component" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InnerException" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InnerMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "component",
    "innerException",
    "innerMessage"
})
@XmlRootElement(name = "TechnicalFault")
public class TechnicalFault {

    @XmlElement(name = "Message", required = true)
    protected String message;
    @XmlElement(name = "Component", required = true)
    protected String component;
    @XmlElement(name = "InnerException", required = true)
    protected String innerException;
    @XmlElement(name = "InnerMessage", required = true)
    protected String innerMessage;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the component property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponent() {
        return component;
    }

    /**
     * Sets the value of the component property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponent(String value) {
        this.component = value;
    }

    /**
     * Gets the value of the innerException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInnerException() {
        return innerException;
    }

    /**
     * Sets the value of the innerException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInnerException(String value) {
        this.innerException = value;
    }

    /**
     * Gets the value of the innerMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInnerMessage() {
        return innerMessage;
    }

    /**
     * Sets the value of the innerMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInnerMessage(String value) {
        this.innerMessage = value;
    }

}
