//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 10:59:28 AM CEST 
//


package org.opensmartgridplatform.schemas.security.secretmanagement._2020._05;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypedSecrets complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypedSecrets"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="16"&gt;
 *         &lt;element name="TypedSecret" type="{http://www.opensmartgridplatform.org/schemas/security/secretmanagement/2020/05}TypedSecret"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypedSecrets", propOrder = {
    "typedSecret"
})
public class TypedSecrets {

    @XmlElement(name = "TypedSecret", required = true)
    protected List<TypedSecret> typedSecret;

    /**
     * Gets the value of the typedSecret property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typedSecret property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypedSecret().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypedSecret }
     * 
     * 
     */
    public List<TypedSecret> getTypedSecret() {
        if (typedSecret == null) {
            typedSecret = new ArrayList<TypedSecret>();
        }
        return this.typedSecret;
    }

}
