package com.alliander.osgp.adapter.protocol.oslp.infra.messaging;

public enum DeviceRequestMessageType {
    GET_FIRMWARE_VERSION, UPDATE_FIRMWARE, START_SELF_TEST, STOP_SELF_TEST, SET_REBOOT, SET_EVENT_NOTIFICATIONS, SET_CONFIGURATION, GET_CONFIGURATION, GET_STATUS, GET_LIGHT_STATUS, RESUME_SCHEDULE, SET_LIGHT, SET_LIGHT_SCHEDULE, SET_TRANSITION, GET_ACTUAL_POWER_USAGE, GET_POWER_USAGE_HISTORY, GET_TARIFF_STATUS, SET_TARIFF_SCHEDULE, UPDATE_KEY, REVOKE_KEY
}
