// SPDX-FileCopyrightText: Copyright Contributors to the GXF project
//
// SPDX-License-Identifier: Apache-2.0

package org.opensmartgridplatform.dto.valueobjects.smartmetering;

public enum AlarmTypeDto {
  CLOCK_INVALID,
  REPLACE_BATTERY,
  POWER_UP,
  AUXILIARY_EVENT,
  CONFIGURATION_CHANGED,
  PROGRAM_MEMORY_ERROR,
  RAM_ERROR,
  NV_MEMORY_ERROR,
  MEASUREMENT_SYSTEM_ERROR,
  WATCHDOG_ERROR,
  FRAUD_ATTEMPT,
  COMMUNICATION_ERROR_M_BUS_CHANNEL_1,
  COMMUNICATION_ERROR_M_BUS_CHANNEL_2,
  COMMUNICATION_ERROR_M_BUS_CHANNEL_3,
  COMMUNICATION_ERROR_M_BUS_CHANNEL_4,
  FRAUD_ATTEMPT_M_BUS_CHANNEL_1,
  FRAUD_ATTEMPT_M_BUS_CHANNEL_2,
  FRAUD_ATTEMPT_M_BUS_CHANNEL_3,
  FRAUD_ATTEMPT_M_BUS_CHANNEL_4,
  LAST_GASP,
  LAST_GASP_TEST,
  NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_1,
  NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_2,
  NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_3,
  NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_4,
  PHASE_OUTAGE_DETECTED_L1,
  PHASE_OUTAGE_DETECTED_L2,
  PHASE_OUTAGE_DETECTED_L3,
  PHASE_OUTAGE_TEST_INDICATION,
  THD_OVERLIMIT_IN_PHASE_L1,
  THD_OVERLIMIT_IN_PHASE_L2,
  THD_OVERLIMIT_IN_PHASE_L3,
  THD_LONG_OVERLIMIT_IN_PHASE_L1,
  THD_LONG_OVERLIMIT_IN_PHASE_L2,
  THD_LONG_OVERLIMIT_IN_PHASE_L3,
  VOLTAGE_SAG_IN_PHASE_DETECTED_L1,
  VOLTAGE_SAG_IN_PHASE_DETECTED_L2,
  VOLTAGE_SAG_IN_PHASE_DETECTED_L3,
  VOLTAGE_SWELL_IN_PHASE_DETECTED_L1,
  VOLTAGE_SWELL_IN_PHASE_DETECTED_L2,
  VOLTAGE_SWELL_IN_PHASE_DETECTED_L3
}
