singleServerConfig:
  address: "rediss://localhost:6379"
  sslEnableEndpointIdentification: false
  sslKeystore: "file:temp/keystore.jks" # Generated in application, based on property: redisson.tmp.keystore.location
  sslKeystorePassword: "" # Generated in application, leave empty
  sslTruststore: "file:temp/truststore.jks" # Generated in application, based on property: redisson.tmp.truststore.location
  sslTruststorePassword: "" # Generated in application, leave empty
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.Kryo5Codec> { }
transportMode: "NIO"
