//  SPDX-FileCopyrightText: Copyright Contributors to the GXF project
//  SPDX-License-Identifier: Apache-2.0
package org.opensmartgridplatform.adapter.domain.smartmetering.application.services;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.opensmartgridplatform.domain.core.entities.SmartMeter;
import org.opensmartgridplatform.dto.valueobjects.smartmetering.EventDto;
import org.opensmartgridplatform.dto.valueobjects.smartmetering.EventMessageDataResponseDto;
import org.opensmartgridplatform.dto.valueobjects.smartmetering.EventTypeDto;
import org.opensmartgridplatform.shared.exceptionhandling.ComponentType;
import org.opensmartgridplatform.shared.exceptionhandling.FunctionalException;
import org.opensmartgridplatform.shared.exceptionhandling.FunctionalExceptionType;
import org.opensmartgridplatform.shared.infra.jms.MessageMetadata;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service(value = "eventService")
public class EventService {

  final DomainHelperService domainHelperService;
  final Map<Integer, List<EventTypeDtoLookup>> eventTypsByCode;

  private static final Logger LOGGER = LoggerFactory.getLogger(EventService.class);

  public EventService(final DomainHelperService domainHelperService) {
    this.domainHelperService = domainHelperService;
    this.eventTypsByCode =
        Arrays.stream(EventTypeDtoLookup.values())
            .collect(Collectors.groupingBy(EventTypeDtoLookup::getEventCode));
  }

  public void enrichEvents(
      final MessageMetadata deviceMessageMetadata, final EventMessageDataResponseDto responseDto)
      throws FunctionalException {

    LOGGER.info(
        "Enrich EventMessageDataResponse with EventTypes for device: {}",
        deviceMessageMetadata.getDeviceIdentification());
    final SmartMeter smartMeter =
        this.domainHelperService.findSmartMeter(deviceMessageMetadata.getDeviceIdentification());

    for (final EventDto eventDto : responseDto.getEvents()) {
      final String protocolName =
          smartMeter.getProtocolInfo() != null ? smartMeter.getProtocolInfo().getProtocol() : null;

      final EventTypeDto eventTypeDto = this.determineEventType(eventDto, protocolName);
      eventDto.setEventTypeDto(eventTypeDto);
    }
  }

  private EventTypeDto determineEventType(final EventDto eventDto, final String protocolName)
      throws FunctionalException {

    final Integer eventCode = eventDto.getEventCode();

    final List<EventTypeDtoLookup> possibleEventTypes = this.eventTypsByCode.get(eventCode);
    if (possibleEventTypes == null) {
      throw new FunctionalException(
          FunctionalExceptionType.VALIDATION_ERROR,
          ComponentType.DOMAIN_SMART_METERING,
          new AssertionError("Event Type should be defined for eventCode: " + eventCode));
    }
    final List<EventTypeDtoLookup> eventTypes =
        possibleEventTypes.stream()
            .filter(
                lookup ->
                    lookup.getProtocol() == null || protocolName.startsWith(lookup.getProtocol()))
            .collect(Collectors.toList());
    if (eventTypes.size() == 1) {
      return eventTypes.get(0).getEventTypeDto();
    } else if (eventTypes.size() > 1) {

      /* Specific EventTypes overrule the Genric ones */
      final List<EventTypeDtoLookup> specificEventTypes =
          eventTypes.stream().filter(lookup -> !lookup.isGeneric()).collect(Collectors.toList());
      if (specificEventTypes.size() == 1) {
        return specificEventTypes.get(0).getEventTypeDto();
      }
    }

    throw new FunctionalException(
        FunctionalExceptionType.VALIDATION_ERROR,
        ComponentType.DOMAIN_SMART_METERING,
        new AssertionError(
            "Exactly one Event Type should be match eventCode: "
                + eventCode
                + ", protocolName: "
                + protocolName));
  }

  enum EventTypeDtoLookup {
    EVENTLOG_CLEARED(EventTypeDto.EVENTLOG_CLEARED, 255, null),
    POWER_FAILURE(EventTypeDto.POWER_FAILURE, 1, null),
    POWER_RETURNED(EventTypeDto.POWER_RETURNED, 2, null),
    CLOCK_UPDATE(EventTypeDto.CLOCK_UPDATE, 3, null),
    CLOCK_ADJUSTED_OLD_TIME(EventTypeDto.CLOCK_ADJUSTED_OLD_TIME, 4, null),
    CLOCK_ADJUSTED_NEW_TIME(EventTypeDto.CLOCK_ADJUSTED_NEW_TIME, 5, null),
    CLOCK_INVALID(EventTypeDto.CLOCK_INVALID, 6, null),
    REPLACE_BATTERY(EventTypeDto.REPLACE_BATTERY, 7, null),
    BATTERY_VOLTAGE_LOW(EventTypeDto.BATTERY_VOLTAGE_LOW, 8, null),
    TARIFF_ACTIVATED(EventTypeDto.TARIFF_ACTIVATED, 9, null),
    ERROR_REGISTER_CLEARED(EventTypeDto.ERROR_REGISTER_CLEARED, 10, null),
    ALARM_REGISTER_CLEARED(EventTypeDto.ALARM_REGISTER_CLEARED, 11, null),
    HARDWARE_ERROR_PROGRAM_MEMORY(EventTypeDto.HARDWARE_ERROR_PROGRAM_MEMORY, 12, null),
    HARDWARE_ERROR_RAM(EventTypeDto.HARDWARE_ERROR_RAM, 13, null),
    HARDWARE_ERROR_NV_MEMORY(EventTypeDto.HARDWARE_ERROR_NV_MEMORY, 14, null),
    WATCHDOG_ERROR(EventTypeDto.WATCHDOG_ERROR, 15, null),
    HARDWARE_ERROR_MEASUREMENT_SYSTEM(EventTypeDto.HARDWARE_ERROR_MEASUREMENT_SYSTEM, 16, null),
    FIRMWARE_READY_FOR_ACTIVATION(EventTypeDto.FIRMWARE_READY_FOR_ACTIVATION, 17, null),
    FIRMWARE_ACTIVATED(EventTypeDto.FIRMWARE_ACTIVATED, 18, null),
    PASSIVE_TARIFF_UPDATED(EventTypeDto.PASSIVE_TARIFF_UPDATED, 19, null),
    SUCCESSFUL_SELFCHECK_AFTER_FIRMWARE_UPDATE(
        EventTypeDto.SUCCESSFUL_SELFCHECK_AFTER_FIRMWARE_UPDATE, 20, null),
    COMMUNICATION_MODULE_REMOVED(EventTypeDto.COMMUNICATION_MODULE_REMOVED, 21, null),
    COMMUNICATION_MODULE_INSERTED(EventTypeDto.COMMUNICATION_MODULE_INSERTED, 22, null),
    ERROR_REGISTER_2_CLEARED(EventTypeDto.ERROR_REGISTER_2_CLEARED, 23, null),
    ALARM_REGISTER_2_CLEARED(EventTypeDto.ALARM_REGISTER_2_CLEARED, 24, null),
    LAST_GASP_TEST(EventTypeDto.LAST_GASP_TEST, 25, null),
    TERMINAL_COVER_REMOVED(EventTypeDto.TERMINAL_COVER_REMOVED, 40, null),
    TERMINAL_COVER_CLOSED(EventTypeDto.TERMINAL_COVER_CLOSED, 41, null),
    STRONG_DC_FIELD_DETECTED(EventTypeDto.STRONG_DC_FIELD_DETECTED, 42, null),
    NO_STRONG_DC_FIELD_ANYMORE(EventTypeDto.NO_STRONG_DC_FIELD_ANYMORE, 43, null),
    METER_COVER_REMOVED(EventTypeDto.METER_COVER_REMOVED, 44, null),
    METER_COVER_CLOSED(EventTypeDto.METER_COVER_CLOSED, 45, null),
    FAILED_LOGIN_ATTEMPT(EventTypeDto.FAILED_LOGIN_ATTEMPT, 46, null),
    CONFIGURATION_CHANGE(EventTypeDto.CONFIGURATION_CHANGE, 47, null),
    MODULE_COVER_OPENED(EventTypeDto.MODULE_COVER_OPENED, 48, null),
    MODULE_COVER_CLOSED(EventTypeDto.MODULE_COVER_CLOSED, 49, null),
    METROLOGICAL_MAINTENANCE(EventTypeDto.METROLOGICAL_MAINTENANCE, 71, null),
    TECHNICAL_MAINTENANCE(EventTypeDto.TECHNICAL_MAINTENANCE, 72, null),
    RETRIEVE_METER_READINGS_E(EventTypeDto.RETRIEVE_METER_READINGS_E, 73, null),
    RETRIEVE_METER_READINGS_G(EventTypeDto.RETRIEVE_METER_READINGS_G, 74, null),
    RETRIEVE_INTERVAL_DATA_E(EventTypeDto.RETRIEVE_INTERVAL_DATA_E, 75, null),
    RETRIEVE_INTERVAL_DATA_G(EventTypeDto.RETRIEVE_INTERVAL_DATA_G, 76, null),
    UNDER_VOLTAGE_L1(EventTypeDto.UNDER_VOLTAGE_L1, 77, null),
    UNDER_VOLTAGE_L2(EventTypeDto.UNDER_VOLTAGE_L2, 78, null),
    UNDER_VOLTAGE_L3(EventTypeDto.UNDER_VOLTAGE_L3, 79, null),
    PV_VOLTAGE_SAG_L1(EventTypeDto.PV_VOLTAGE_SAG_L1, 80, "DSMR"),
    PV_VOLTAGE_SAG_L2(EventTypeDto.PV_VOLTAGE_SAG_L2, 81, "DSMR"),
    PV_VOLTAGE_SAG_L3(EventTypeDto.PV_VOLTAGE_SAG_L3, 82, "DSMR"),
    PV_VOLTAGE_SWELL_L1(EventTypeDto.PV_VOLTAGE_SWELL_L1, 83, "DSMR"),
    PV_VOLTAGE_SWELL_L2(EventTypeDto.PV_VOLTAGE_SWELL_L2, 84, "DSMR"),
    PV_VOLTAGE_SWELL_L3(EventTypeDto.PV_VOLTAGE_SWELL_L3, 85, "DSMR"),
    OVER_VOLTAGE_L1(EventTypeDto.OVER_VOLTAGE_L1, 80, "SMR"),
    OVER_VOLTAGE_L2(EventTypeDto.OVER_VOLTAGE_L2, 81, "SMR"),
    OVER_VOLTAGE_L3(EventTypeDto.OVER_VOLTAGE_L3, 82, "SMR"),
    VOLTAGE_L1_NORMAL(EventTypeDto.VOLTAGE_L1_NORMAL, 83, "SMR"),
    VOLTAGE_L2_NORMAL(EventTypeDto.VOLTAGE_L2_NORMAL, 84, "SMR"),
    VOLTAGE_L3_NORMAL(EventTypeDto.VOLTAGE_L3_NORMAL, 85, "SMR"),
    PHASE_OUTAGE_L1(EventTypeDto.PHASE_OUTAGE_L1, 86, null),
    PHASE_OUTAGE_L2(EventTypeDto.PHASE_OUTAGE_L2, 87, null),
    PHASE_OUTAGE_L3(EventTypeDto.PHASE_OUTAGE_L3, 88, null),
    PHASE_OUTAGE_TEST(EventTypeDto.PHASE_OUTAGE_TEST, 89, null),
    PHASE_RETURNED_L1(EventTypeDto.PHASE_RETURNED_L1, 90, null),
    PHASE_RETURNED_L2(EventTypeDto.PHASE_RETURNED_L2, 91, null),
    PHASE_RETURNED_L3(EventTypeDto.PHASE_RETURNED_L3, 92, null),
    VOLTAGE_SAG_IN_PHASE_L1(EventTypeDto.VOLTAGE_SAG_IN_PHASE_L1, 93, null),
    VOLTAGE_SAG_IN_PHASE_L2(EventTypeDto.VOLTAGE_SAG_IN_PHASE_L2, 94, null),
    VOLTAGE_SAG_IN_PHASE_L3(EventTypeDto.VOLTAGE_SAG_IN_PHASE_L3, 95, null),
    VOLTAGE_SWELL_IN_PHASE_L1(EventTypeDto.VOLTAGE_SWELL_IN_PHASE_L1, 96, null),
    VOLTAGE_SWELL_IN_PHASE_L2(EventTypeDto.VOLTAGE_SWELL_IN_PHASE_L2, 97, null),
    VOLTAGE_SWELL_IN_PHASE_L3(EventTypeDto.VOLTAGE_SWELL_IN_PHASE_L3, 98, null),
    LAST_GASP(EventTypeDto.LAST_GASP, 99, null),
    COMMUNICATION_ERROR_M_BUS_CHANNEL_1(
        EventTypeDto.COMMUNICATION_ERROR_M_BUS_CHANNEL_1, 100, null),
    COMMUNICATION_OK_M_BUS_CHANNEL_1(EventTypeDto.COMMUNICATION_OK_M_BUS_CHANNEL_1, 101, null),
    REPLACE_BATTERY_M_BUS_CHANNEL_1(EventTypeDto.REPLACE_BATTERY_M_BUS_CHANNEL_1, 102, null),
    FRAUD_ATTEMPT_M_BUS_CHANNEL_1(EventTypeDto.FRAUD_ATTEMPT_M_BUS_CHANNEL_1, 103, null),
    CLOCK_ADJUSTED_M_BUS_CHANNEL_1(EventTypeDto.CLOCK_ADJUSTED_M_BUS_CHANNEL_1, 104, null),
    NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_1(
        EventTypeDto.NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_1, 105, null),
    PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_1(
        EventTypeDto.PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_1, 106, null),
    DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_1(
        EventTypeDto.DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_1, 107, null),
    COMMUNICATION_ERROR_M_BUS_CHANNEL_2(
        EventTypeDto.COMMUNICATION_ERROR_M_BUS_CHANNEL_2, 110, null),
    COMMUNICATION_OK_M_BUS_CHANNEL_2(EventTypeDto.COMMUNICATION_OK_M_BUS_CHANNEL_2, 111, null),
    REPLACE_BATTERY_M_BUS_CHANNEL_2(EventTypeDto.REPLACE_BATTERY_M_BUS_CHANNEL_2, 112, null),
    FRAUD_ATTEMPT_M_BUS_CHANNEL_2(EventTypeDto.FRAUD_ATTEMPT_M_BUS_CHANNEL_2, 113, null),
    CLOCK_ADJUSTED_M_BUS_CHANNEL_2(EventTypeDto.CLOCK_ADJUSTED_M_BUS_CHANNEL_2, 114, null),
    NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_2(
        EventTypeDto.NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_2, 115, null),
    PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_2(
        EventTypeDto.PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_2, 116, null),
    DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_2(
        EventTypeDto.DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_2, 117, null),
    COMMUNICATION_ERROR_M_BUS_CHANNEL_3(
        EventTypeDto.COMMUNICATION_ERROR_M_BUS_CHANNEL_3, 120, null),
    COMMUNICATION_OK_M_BUS_CHANNEL_3(EventTypeDto.COMMUNICATION_OK_M_BUS_CHANNEL_3, 121, null),
    REPLACE_BATTERY_M_BUS_CHANNEL_3(EventTypeDto.REPLACE_BATTERY_M_BUS_CHANNEL_3, 122, null),
    FRAUD_ATTEMPT_M_BUS_CHANNEL_3(EventTypeDto.FRAUD_ATTEMPT_M_BUS_CHANNEL_3, 123, null),
    CLOCK_ADJUSTED_M_BUS_CHANNEL_3(EventTypeDto.CLOCK_ADJUSTED_M_BUS_CHANNEL_3, 124, null),
    NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_3(
        EventTypeDto.NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_3, 125, null),
    PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_3(
        EventTypeDto.PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_3, 126, null),
    DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_3(
        EventTypeDto.DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_3, 127, null),
    COMMUNICATION_ERROR_M_BUS_CHANNEL_4(
        EventTypeDto.COMMUNICATION_ERROR_M_BUS_CHANNEL_4, 130, null),
    COMMUNICATION_OK_M_BUS_CHANNEL_4(EventTypeDto.COMMUNICATION_OK_M_BUS_CHANNEL_4, 131, null),
    REPLACE_BATTERY_M_BUS_CHANNEL_4(EventTypeDto.REPLACE_BATTERY_M_BUS_CHANNEL_4, 132, null),
    FRAUD_ATTEMPT_M_BUS_CHANNEL_4(EventTypeDto.FRAUD_ATTEMPT_M_BUS_CHANNEL_4, 133, null),
    CLOCK_ADJUSTED_M_BUS_CHANNEL_4(EventTypeDto.CLOCK_ADJUSTED_M_BUS_CHANNEL_4, 134, null),
    NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_4(
        EventTypeDto.NEW_M_BUS_DEVICE_DISCOVERED_CHANNEL_4, 135, null),
    PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_4(
        EventTypeDto.PERMANENT_ERROR_FROM_M_BUS_DEVICE_CHANNEL_4, 136, null),
    DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_4(
        EventTypeDto.DEAD_BATTERY_ERROR_M_BUS_DEVICE_CHANNEL_4, 137, null),
    MANUFACTURER_SPECIFIC_230(EventTypeDto.MANUFACTURER_SPECIFIC_230, 230, null),
    MANUFACTURER_SPECIFIC_231(EventTypeDto.MANUFACTURER_SPECIFIC_231, 231, null),
    MANUFACTURER_SPECIFIC_232(EventTypeDto.MANUFACTURER_SPECIFIC_232, 232, null),
    MANUFACTURER_SPECIFIC_233(EventTypeDto.MANUFACTURER_SPECIFIC_233, 233, null),
    MANUFACTURER_SPECIFIC_234(EventTypeDto.MANUFACTURER_SPECIFIC_234, 234, null),
    MANUFACTURER_SPECIFIC_235(EventTypeDto.MANUFACTURER_SPECIFIC_235, 235, null),
    MANUFACTURER_SPECIFIC_236(EventTypeDto.MANUFACTURER_SPECIFIC_236, 236, null),
    MANUFACTURER_SPECIFIC_237(EventTypeDto.MANUFACTURER_SPECIFIC_237, 237, null),
    MANUFACTURER_SPECIFIC_238(EventTypeDto.MANUFACTURER_SPECIFIC_238, 238, null),
    MANUFACTURER_SPECIFIC_239(EventTypeDto.MANUFACTURER_SPECIFIC_239, 239, null),
    MANUFACTURER_SPECIFIC_240(EventTypeDto.MANUFACTURER_SPECIFIC_240, 240, null),
    MANUFACTURER_SPECIFIC_241(EventTypeDto.MANUFACTURER_SPECIFIC_241, 241, null),
    MANUFACTURER_SPECIFIC_242(EventTypeDto.MANUFACTURER_SPECIFIC_242, 242, null),
    MANUFACTURER_SPECIFIC_243(EventTypeDto.MANUFACTURER_SPECIFIC_243, 243, null),
    MANUFACTURER_SPECIFIC_244(EventTypeDto.MANUFACTURER_SPECIFIC_244, 244, null),
    MANUFACTURER_SPECIFIC_245(EventTypeDto.MANUFACTURER_SPECIFIC_245, 245, null),
    MANUFACTURER_SPECIFIC_246(EventTypeDto.MANUFACTURER_SPECIFIC_246, 246, null),
    MANUFACTURER_SPECIFIC_247(EventTypeDto.MANUFACTURER_SPECIFIC_247, 247, null),
    MANUFACTURER_SPECIFIC_248(EventTypeDto.MANUFACTURER_SPECIFIC_248, 248, null),
    MANUFACTURER_SPECIFIC_249(EventTypeDto.MANUFACTURER_SPECIFIC_249, 249, null),

    AUXILIARY_EVENTLOG_CLEARED(EventTypeDto.AUXILIARY_EVENTLOG_CLEARED, 0xFFFF, null),
    MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_1, 0x1000, null),
    MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_1, 0x1001, null),
    MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_1, 0x1002, null),
    MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_1, 0x1003, null),
    MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_1, 0x1004, null),
    MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_1, 0x1005, null),
    MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_1, 0x1006, null),
    MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_1(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_1, 0x1007, null),
    MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_2, 0x1100, null),
    MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_2, 0x1101, null),
    MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_2, 0x1102, null),
    MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_2, 0x1103, null),
    MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_2, 0x1104, null),
    MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_2, 0x1105, null),
    MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_2, 0x1106, null),
    MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_2(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_2, 0x1107, null),
    MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_3, 0x1200, null),
    MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_3, 0x1201, null),
    MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_3, 0x1202, null),
    MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_3, 0x1203, null),
    MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_3, 0x1204, null),
    MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_3, 0x1205, null),
    MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_3, 0x1206, null),
    MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_3(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_3, 0x1207, null),
    MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_SUCCESSFUL_CHANNEL_4, 0x1300, null),
    MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_BLOCK_SIZE_NOT_SUPPORTED_CHANNEL_4, 0x1301, null),
    MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_SIZE_TOO_BIG_CHANNEL_4, 0x1302, null),
    MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_BLOCK_NUMBER_CHANNEL_4, 0x1303, null),
    MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_DATA_RECEIVE_ERROR_CHANNEL_4, 0x1304, null),
    MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_IMAGE_NOT_COMPLETE_ERROR_CHANNEL_4, 0x1305, null),
    MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_SECURITY_ERROR_CHANNEL_4, 0x1306, null),
    MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_4(
        EventTypeDto.MBUS_FW_UPGRADE_INVALID_FIRMWARE_FOR_THIS_DEVICE_CHANNEL_4, 0x1307, null),

    MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_1, 0x8080, null),
    MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_1, 0x8081, null),
    MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_1, 0x8082, null),
    MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_1, 0x8083, null),
    MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_1, 0x8084, null),
    MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_1, 0x8085, null),
    MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_1, 0x8086, null),
    MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_1, 0x8087, null),
    MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_1, 0x8088, null),
    MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_1, 0x8089, null),
    MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_1, 0x808A, null),
    MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_1, 0x808B, null),
    MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_1, 0x808C, null),
    MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_1, 0x808D, null),
    MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_1, 0x808E, null),
    MBUS_STATUS_BIT_15_RESERVED_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_15_RESERVED_CHANNEL_1, 0x808F, null),
    MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_1, 0x8090, null),
    MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_1, 0x8091, null),
    MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_1, 0x8092, null),
    MBUS_STATUS_BIT_18_RESERVED_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_18_RESERVED_CHANNEL_1, 0x8093, null),
    MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x8094, null),
    MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x8095, null),
    MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x8096, null),
    MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x8097, null),
    MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x8098, null),
    MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x8099, null),
    MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x809A, null),
    MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x809B, null),
    MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x809C, null),
    MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x809D, null),
    MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x809E, null),
    MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_1(
        EventTypeDto.MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_1, 0x809F, null),
    KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_1(
        EventTypeDto.KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_1, 0x80A0, null),
    KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_1(
        EventTypeDto.KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_1, 0x80A1, null),

    MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_2, 0x8180, null),
    MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_2, 0x8181, null),
    MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_2, 0x8182, null),
    MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_2, 0x8183, null),
    MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_2, 0x8184, null),
    MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_2, 0x8185, null),
    MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_2, 0x8186, null),
    MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_2, 0x8187, null),
    MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_2, 0x8188, null),
    MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_2, 0x8189, null),
    MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_2, 0x818A, null),
    MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_2, 0x818B, null),
    MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_2, 0x818C, null),
    MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_2, 0x818D, null),
    MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_2, 0x818E, null),
    MBUS_STATUS_BIT_15_RESERVED_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_15_RESERVED_CHANNEL_2, 0x818F, null),
    MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_2, 0x8190, null),
    MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_2, 0x8191, null),
    MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_2, 0x8192, null),
    MBUS_STATUS_BIT_18_RESERVED_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_18_RESERVED_CHANNEL_2, 0x8193, null),
    MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x8194, null),
    MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x8195, null),
    MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x8196, null),
    MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x8197, null),
    MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x8198, null),
    MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x8199, null),
    MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x819A, null),
    MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x819B, null),
    MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x819C, null),
    MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x819D, null),
    MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x819E, null),
    MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_2(
        EventTypeDto.MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_2, 0x819F, null),
    KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_2(
        EventTypeDto.KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_2, 0x81A0, null),
    KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_2(
        EventTypeDto.KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_2, 0x81A1, null),

    MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_3, 0x8280, null),
    MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_3, 0x8281, null),
    MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_3, 0x8282, null),
    MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_3, 0x8283, null),
    MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_3, 0x8284, null),
    MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_3, 0x8285, null),
    MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_3, 0x8286, null),
    MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_3, 0x8287, null),
    MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_3, 0x8288, null),
    MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_3, 0x8289, null),
    MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_3, 0x828A, null),
    MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_3, 0x828B, null),
    MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_3, 0x828C, null),
    MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_3, 0x828D, null),
    MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_3, 0x828E, null),
    MBUS_STATUS_BIT_15_RESERVED_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_15_RESERVED_CHANNEL_3, 0x828F, null),
    MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_3, 0x8290, null),
    MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_3, 0x8291, null),
    MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_3, 0x8292, null),
    MBUS_STATUS_BIT_18_RESERVED_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_18_RESERVED_CHANNEL_3, 0x8293, null),
    MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x8294, null),
    MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x8295, null),
    MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x8296, null),
    MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x8297, null),
    MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x8298, null),
    MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x8299, null),
    MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x829A, null),
    MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x829B, null),
    MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x829C, null),
    MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x829D, null),
    MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x829E, null),
    MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_3(
        EventTypeDto.MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_3, 0x829F, null),
    KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_3(
        EventTypeDto.KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_3, 0x82A0, null),
    KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_3(
        EventTypeDto.KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_3, 0x82A1, null),

    MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_0_BATTERY_LOW_CHANNEL_4, 0x8380, null),
    MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_1_BATTERY_CONSUMPTION_TOO_HIGH_CHANNEL_4, 0x8381, null),
    MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_2_REVERSE_FLOW_CHANNEL_4, 0x8382, null),
    MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_3_TAMPER_P2_CHANNEL_4, 0x8383, null),
    MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_4_TAMPER_P0_CHANNEL_4, 0x8384, null),
    MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_5_TAMPER_CASE_CHANNEL_4, 0x8385, null),
    MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_6_TAMPER_MAGNETIC_CHANNEL_4, 0x8386, null),
    MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_7_TEMP_OUT_OF_RANGE_CHANNEL_4, 0x8387, null),
    MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_8_CLOCK_SYNC_ERROR_CHANNEL_4, 0x8388, null),
    MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_9_SW_ERROR_CHANNEL_4, 0x8389, null),
    MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_10_WATCHDOG_ERROR_CHANNEL_4, 0x838A, null),
    MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_11_SYSTEM_HW_ERROR_CHANNEL_4, 0x838B, null),
    MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_12_CFG_CALIBRATION_ERROR_CHANNEL_4, 0x838C, null),
    MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_13_HIGH_FLOW_GREATER_THAN_QMAX_CHANNEL_4, 0x838D, null),
    MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_14_TEMP_SENSOR_ERROR_CHANNEL_4, 0x838E, null),
    MBUS_STATUS_BIT_15_RESERVED_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_15_RESERVED_CHANNEL_4, 0x838F, null),
    MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_16_P0_ENABLED_CHANNEL_4, 0x8390, null),
    MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_17_NEW_KEY_ACCEPTED_CHANNEL_4, 0x8391, null),
    MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_18_NEW_KEY_REJECTED_CHANNEL_4, 0x8392, null),
    MBUS_STATUS_BIT_18_RESERVED_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_18_RESERVED_CHANNEL_4, 0x8393, null),
    MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_20_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x8394, null),
    MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_21_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x8395, null),
    MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_22_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x8396, null),
    MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_23_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x8397, null),
    MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_24_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x8398, null),
    MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_25_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x8399, null),
    MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_26_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x839A, null),
    MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_27_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x839B, null),
    MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_28_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x839C, null),
    MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_29_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x839D, null),
    MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_30_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x839E, null),
    MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_4(
        EventTypeDto.MBUS_STATUS_BIT_31_MANUFACTURER_SPECIFIC_CHANNEL_4, 0x839F, null),
    KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_4(
        EventTypeDto.KEY_SENT_TO_MBUS_DEVICE_ON_CHANNEL_4, 0x83A0, null),
    KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_4(
        EventTypeDto.KEY_ACKNOWLEDGED_BY_MBUS_DEVICE_ON_CHANNEL_4, 0x83A1, null);

    private final EventTypeDto eventTypeDto;
    private final int eventCode;
    private final String protocol;

    EventTypeDtoLookup(
        final EventTypeDto eventTypeDto, final int eventCode, final String protocol) {
      this.eventTypeDto = eventTypeDto;
      this.eventCode = eventCode;
      this.protocol = protocol;
    }

    public EventTypeDto getEventTypeDto() {
      return this.eventTypeDto;
    }

    public int getEventCode() {
      return this.eventCode;
    }

    public String getProtocol() {
      return this.protocol;
    }

    public boolean isGeneric() {
      return this.getProtocol() == null;
    }
  }
}
