pipelineJob('example') {
    description('Test build job. [Job generated by Job DSL]')
    definition {
        cps {
            script(readFileFromWorkspace('jenkins/pipeline/test-build.jenkinsfile'))
        }
    }
    properties {
        pipelineTriggers {
            triggers {
                cron('H 21 * * *')
            }
        }
    }
}
