@SmartMetering @Platform @SmartMeteringMonitoring
Feature: SmartMetering Monitoring - Get Actual Power Quality
  As a grid operator
  I want to be able to get the actual power quality from a device
  So I can see them when investigating some issue

  Background:
    Given a dlms device
      | DeviceIdentification     | TEST1024000000001 |
      | DeviceType               | SMART_METER_E     |
      | SelectiveAccessSupported | true              |

  Scenario: Get the actual power quality public from a device
    When the get actual power quality request is received
      | DeviceIdentification | TEST1024000000001 |
      | ProfileType          |            PUBLIC |
    Then the actual power quality result should be returned
      | NumberOfCaptureObjects          |                15 |
      | NumberOfActualValues            |                15 |
      | DeviceIdentification            | TEST1024000000001 |
      | CaptureObject_ClassId_1         |                 8 |
      | CaptureObject_LogicalName_1     | 0.0.1.0.0.255     |
      | CaptureObject_AttributeIndex_1  |                 2 |
      | CaptureObject_DataIndex_1       |                 0 |
      | CaptureObject_ClassId_2         |                 3 |
      | CaptureObject_LogicalName_2     | 1.0.32.7.0.255    |
      | CaptureObject_AttributeIndex_2  |                 2 |
      | CaptureObject_DataIndex_2       |                 0 |
      | CaptureObject_Unit_2            | V                 |
      | CaptureObject_ClassId_3         |                 3 |
      | CaptureObject_LogicalName_3     | 1.0.52.7.0.255    |
      | CaptureObject_AttributeIndex_3  |                 2 |
      | CaptureObject_DataIndex_3       |                 0 |
      | CaptureObject_Unit_3            | V                 |
      | CaptureObject_ClassId_4         |                 3 |
      | CaptureObject_LogicalName_4     | 1.0.72.7.0.255    |
      | CaptureObject_AttributeIndex_4  |                 2 |
      | CaptureObject_DataIndex_4       |                 0 |
      | CaptureObject_Unit_4            | V                 |
      | CaptureObject_ClassId_5         |                 3 |
      | CaptureObject_LogicalName_5     | 1.0.32.24.0.255   |
      | CaptureObject_AttributeIndex_5  |                 2 |
      | CaptureObject_DataIndex_5       |                 0 |
      | CaptureObject_Unit_5            | V                 |
      | CaptureObject_ClassId_6         |                 3 |
      | CaptureObject_LogicalName_6     | 1.0.52.24.0.255   |
      | CaptureObject_AttributeIndex_6  |                 2 |
      | CaptureObject_DataIndex_6       |                 0 |
      | CaptureObject_Unit_6            | V                 |
      | CaptureObject_ClassId_7         |                 3 |
      | CaptureObject_LogicalName_7     | 1.0.72.24.0.255   |
      | CaptureObject_AttributeIndex_7  |                 2 |
      | CaptureObject_DataIndex_7       |                 0 |
      | CaptureObject_Unit_7            | V                 |
      | CaptureObject_ClassId_8         |                 1 |
      | CaptureObject_LogicalName_8     | 0.0.96.7.9.255    |
      | CaptureObject_AttributeIndex_8  |                 2 |
      | CaptureObject_DataIndex_8       |                 0 |
      | CaptureObject_ClassId_9         |                 1 |
      | CaptureObject_LogicalName_9     | 0.0.96.7.21.255   |
      | CaptureObject_AttributeIndex_9  |                 2 |
      | CaptureObject_DataIndex_9       |                 0 |
      | CaptureObject_ClassId_10        |                 1 |
      | CaptureObject_LogicalName_10    | 1.0.32.32.0.255   |
      | CaptureObject_AttributeIndex_10 |                 2 |
      | CaptureObject_DataIndex_10      |                 0 |
      | CaptureObject_ClassId_11        |                 1 |
      | CaptureObject_LogicalName_11    | 1.0.52.32.0.255   |
      | CaptureObject_AttributeIndex_11 |                 2 |
      | CaptureObject_DataIndex_11      |                 0 |
      | CaptureObject_ClassId_12        |                 1 |
      | CaptureObject_LogicalName_12    | 1.0.72.32.0.255   |
      | CaptureObject_AttributeIndex_12 |                 2 |
      | CaptureObject_DataIndex_12      |                 0 |
      | CaptureObject_ClassId_13        |                 1 |
      | CaptureObject_LogicalName_13    | 1.0.32.36.0.255   |
      | CaptureObject_AttributeIndex_13 |                 2 |
      | CaptureObject_DataIndex_13      |                 0 |
      | CaptureObject_ClassId_14        |                 1 |
      | CaptureObject_LogicalName_14    | 1.0.52.36.0.255   |
      | CaptureObject_AttributeIndex_14 |                 2 |
      | CaptureObject_DataIndex_14      |                 0 |
      | CaptureObject_ClassId_15        |                 1 |
      | CaptureObject_LogicalName_15    | 1.0.72.36.0.255   |
      | CaptureObject_AttributeIndex_15 |                 2 |
      | CaptureObject_DataIndex_15      |                 0 |

  Scenario: Get the actual power quality private from a device
    When the get actual power quality request is received
      | DeviceIdentification | TEST1024000000001 |
      | ProfileType          | PRIVATE           |
    Then the actual power quality result should be returned
      | NumberOfCaptureObjects           |                28 |
      | NumberOfActualValues             |                28 |
      | DeviceIdentification             | TEST1024000000001 |
      | CaptureObject_ClassId_1          |                 8 |
      | CaptureObject_LogicalName_1      |    0.0.1.0.0.255  |
      | CaptureObject_AttributeIndex_1   |                 2 |
      | CaptureObject_DataIndex_1        |                 0 |
      | CaptureObject_ClassId_2          |                 3 |
      | CaptureObject_LogicalName_2      | 1.0.31.7.0.255    |
      | CaptureObject_AttributeIndex_2   |                 2 |
      | CaptureObject_DataIndex_2        |                 0 |
      | CaptureObject_Unit_2             | AMP               |
      | CaptureObject_ClassId_3          |                 3 |
      | CaptureObject_LogicalName_3      | 1.0.51.7.0.255    |
      | CaptureObject_AttributeIndex_3   |                 2 |
      | CaptureObject_DataIndex_3        |                 0 |
      | CaptureObject_Unit_3             | AMP               |
      | CaptureObject_ClassId_4          |                 3 |
      | CaptureObject_LogicalName_4      | 1.0.71.7.0.255    |
      | CaptureObject_AttributeIndex_4   |                 2 |
      | CaptureObject_DataIndex_4        |                 0 |
      | CaptureObject_Unit_4             | AMP               |
      | CaptureObject_ClassId_5          |                 3 |
      | CaptureObject_LogicalName_5      |     1.0.1.7.0.255 |
      | CaptureObject_AttributeIndex_5   |                 2 |
      | CaptureObject_DataIndex_5        |                 0 |
      | CaptureObject_Unit_5             | W                 |
      | CaptureObject_ClassId_6          |                 3 |
      | CaptureObject_LogicalName_6      |     1.0.2.7.0.255 |
      | CaptureObject_AttributeIndex_6   |                 2 |
      | CaptureObject_DataIndex_6        |                 0 |
      | CaptureObject_Unit_6             | W                 |
      | CaptureObject_ClassId_7          |                 3 |
      | CaptureObject_LogicalName_7      | 1.0.21.7.0.255    |
      | CaptureObject_AttributeIndex_7   |                 2 |
      | CaptureObject_DataIndex_7        |                 0 |
      | CaptureObject_Unit_7             | W                 |
      | CaptureObject_ClassId_8          |                 3 |
      | CaptureObject_LogicalName_8      | 1.0.41.7.0.255    |
      | CaptureObject_AttributeIndex_8   |                 2 |
      | CaptureObject_DataIndex_8        |                 0 |
      | CaptureObject_Unit_8             | W                 |
      | CaptureObject_ClassId_9          |                 3 |
      | CaptureObject_LogicalName_9      | 1.0.61.7.0.255    |
      | CaptureObject_AttributeIndex_9   |                 2 |
      | CaptureObject_DataIndex_9        |                 0 |
      | CaptureObject_Unit_9             | W                 |
      | CaptureObject_ClassId_10         |                 3 |
      | CaptureObject_LogicalName_10     | 1.0.22.7.0.255    |
      | CaptureObject_AttributeIndex_10  |                 2 |
      | CaptureObject_DataIndex_10       |                 0 |
      | CaptureObject_Unit_10            | W                 |
      | CaptureObject_ClassId_11         |                 3 |
      | CaptureObject_LogicalName_11     | 1.0.42.7.0.255    |
      | CaptureObject_AttributeIndex_11  |                 2 |
      | CaptureObject_DataIndex_11       |                 0 |
      | CaptureObject_Unit_11            | W                 |
      | CaptureObject_ClassId_12         |                 3 |
      | CaptureObject_LogicalName_12     | 1.0.62.7.0.255    |
      | CaptureObject_AttributeIndex_12  |                 2 |
      | CaptureObject_DataIndex_12       |                 0 |
      | CaptureObject_Unit_12            | W                 |
      | CaptureObject_ClassId_13         |                 3 |
      | CaptureObject_LogicalName_13     |   1.0.31.24.0.255 |
      | CaptureObject_AttributeIndex_13  |                 2 |
      | CaptureObject_DataIndex_13       |                 0 |
      | CaptureObject_Unit_13            | AMP               |
      | CaptureObject_ClassId_14         |                 3 |
      | CaptureObject_LogicalName_14     |   1.0.51.24.0.255 |
      | CaptureObject_AttributeIndex_14  |                 2 |
      | CaptureObject_DataIndex_14       |                 0 |
      | CaptureObject_Unit_14            | AMP               |
      | CaptureObject_ClassId_15         |                 3 |
      | CaptureObject_LogicalName_15     |   1.0.71.24.0.255 |
      | CaptureObject_AttributeIndex_15  |                 2 |
      | CaptureObject_DataIndex_15       |                 0 |
      | CaptureObject_Unit_15            | AMP               |
      | CaptureObject_ClassId_16         |                 3 |
      | CaptureObject_LogicalName_16     | 1.0.21.4.0.255    |
      | CaptureObject_AttributeIndex_16  |                 2 |
      | CaptureObject_DataIndex_16       |                 0 |
      | CaptureObject_Unit_16            | W                 |
      | CaptureObject_ClassId_17         |                 3 |
      | CaptureObject_LogicalName_17     | 1.0.41.4.0.255    |
      | CaptureObject_AttributeIndex_17  |                 2 |
      | CaptureObject_DataIndex_17       |                 0 |
      | CaptureObject_Unit_17            | W                 |
      | CaptureObject_ClassId_18         |                 3 |
      | CaptureObject_LogicalName_18     | 1.0.61.4.0.255    |
      | CaptureObject_AttributeIndex_18  |                 2 |
      | CaptureObject_DataIndex_18       |                 0 |
      | CaptureObject_Unit_18            | W                 |
      | CaptureObject_ClassId_19         |                 3 |
      | CaptureObject_LogicalName_19     | 1.0.22.4.0.255    |
      | CaptureObject_AttributeIndex_19  |                 2 |
      | CaptureObject_DataIndex_19       |                 0 |
      | CaptureObject_Unit_19            | W                 |
      | CaptureObject_ClassId_20         |                 3 |
      | CaptureObject_LogicalName_20     | 1.0.42.4.0.255    |
      | CaptureObject_AttributeIndex_20  |                 2 |
      | CaptureObject_DataIndex_20       |                 0 |
      | CaptureObject_Unit_20            | W                 |
      | CaptureObject_ClassId_21         |                 3 |
      | CaptureObject_LogicalName_21     | 1.0.62.4.0.255    |
      | CaptureObject_AttributeIndex_21  |                 2 |
      | CaptureObject_DataIndex_21       |                 0 |
      | CaptureObject_Unit_21            | W                 |
      | CaptureObject_ClassId_22         |                 3 |
      | CaptureObject_LogicalName_22     | 1.0.23.4.0.255    |
      | CaptureObject_AttributeIndex_22  |                 2 |
      | CaptureObject_DataIndex_22       |                 0 |
      | CaptureObject_Unit_22            | VAR               |
      | CaptureObject_ClassId_23         |                 3 |
      | CaptureObject_LogicalName_23     | 1.0.43.4.0.255    |
      | CaptureObject_AttributeIndex_23  |                 2 |
      | CaptureObject_DataIndex_23       |                 0 |
      | CaptureObject_Unit_23            | VAR               |
      | CaptureObject_ClassId_24         |                 3 |
      | CaptureObject_LogicalName_24     | 1.0.63.4.0.255    |
      | CaptureObject_AttributeIndex_24  |                 2 |
      | CaptureObject_DataIndex_24       |                 0 |
      | CaptureObject_Unit_24            | VAR               |
      | CaptureObject_ClassId_25         |                 3 |
      | CaptureObject_LogicalName_25     | 1.0.24.4.0.255    |
      | CaptureObject_AttributeIndex_25  |                 2 |
      | CaptureObject_DataIndex_25       |                 0 |
      | CaptureObject_Unit_25            | VAR               |
      | CaptureObject_ClassId_26         |                 3 |
      | CaptureObject_LogicalName_26     | 1.0.44.4.0.255    |
      | CaptureObject_AttributeIndex_26  |                 2 |
      | CaptureObject_DataIndex_26       |                 0 |
      | CaptureObject_Unit_26            | VAR               |
      | CaptureObject_ClassId_27         |                 3 |
      | CaptureObject_LogicalName_27     | 1.0.64.4.0.255    |
      | CaptureObject_AttributeIndex_27  |                 2 |
      | CaptureObject_DataIndex_27       |                 0 |
      | CaptureObject_Unit_27            | VAR               |
      | CaptureObject_ClassId_28         |                 3 |
      | CaptureObject_LogicalName_28     | 1.0.90.7.0.255    |
      | CaptureObject_AttributeIndex_28  |                 2 |
      | CaptureObject_DataIndex_28       |                 0 |
      | CaptureObject_Unit_28            | AMP               |

  Scenario: Do not refuse an operation with an inactive device
    Given a dlms device
      | DeviceIdentification  | E9998000014123414 |
      | DeviceType            | SMART_METER_E     |
      | DeviceLifecycleStatus | NEW_IN_INVENTORY  |
    When the get actual power quality request is received
      | DeviceIdentification   | E9998000014123414 |
      | ProfileType            |           PRIVATE |
    Then the actual power quality result should be returned
      | DeviceIdentification   | E9998000014123414 |
      | NumberOfCaptureObjects |                28 |
      | NumberOfActualValues   |                28 |
