package com.alliander.osgp.domain.core.valueobjects;

public enum DeviceFunction {
    START_SELF_TEST, STOP_SELF_TEST, SET_LIGHT, GET_DEVICE_AUTHORIZATION, SET_EVENT_NOTIFICATIONS, SET_DEVICE_AUTHORIZATION, GET_EVENT_NOTIFICATIONS, UPDATE_FIRMWARE, GET_FIRMWARE_VERSION, SET_TARIFF_SCHEDULE, SET_LIGHT_SCHEDULE, SET_CONFIGURATION, GET_CONFIGURATION, GET_STATUS, GET_LIGHT_STATUS, GET_TARIFF_STATUS, REMOVE_DEVICE, GET_ACTUAL_POWER_USAGE, GET_POWER_USAGE_HISTORY, RESUME_SCHEDULE, SET_REBOOT, SET_TRANSITION, UPDATE_KEY, REVOKE_KEY, FIND_SCHEDULED_TASKS, REGISTER_DEVICE, ADD_EVENT_NOTIFICATION
}
