package com.alliander.osgp.domain.core.valueobjects;

public enum PlatformFunction {
    CREATE_ORGANISATION, REMOVE_ORGANISATION, CHANGE_ORGANISATION, GET_ORGANISATIONS, GET_MESSAGES, GET_DEVICE_NO_OWNER, FIND_DEVICES, SET_OWNER, UPDATE_KEY, REVOKE_KEY, FIND_SCHEDULED_TASKS
}
