// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: envelope.proto
// Protobuf Java Version: 4.31.0

package org.opensmartgridplatform.oslp;

@com.google.protobuf.Generated
public final class Envelope {
  private Envelope() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      Envelope.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OslpEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oslp.OslpEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes SecurityKey = 1;</code>
     * @return Whether the securityKey field is set.
     */
    boolean hasSecurityKey();
    /**
     * <code>bytes SecurityKey = 1;</code>
     * @return The securityKey.
     */
    com.google.protobuf.ByteString getSecurityKey();

    /**
     * <code>bytes SequenceNumber = 2;</code>
     * @return Whether the sequenceNumber field is set.
     */
    boolean hasSequenceNumber();
    /**
     * <code>bytes SequenceNumber = 2;</code>
     * @return The sequenceNumber.
     */
    com.google.protobuf.ByteString getSequenceNumber();

    /**
     * <code>bytes DeviceId = 3;</code>
     * @return Whether the deviceId field is set.
     */
    boolean hasDeviceId();
    /**
     * <code>bytes DeviceId = 3;</code>
     * @return The deviceId.
     */
    com.google.protobuf.ByteString getDeviceId();

    /**
     * <code>bytes LengthIndicator = 4;</code>
     * @return Whether the lengthIndicator field is set.
     */
    boolean hasLengthIndicator();
    /**
     * <code>bytes LengthIndicator = 4;</code>
     * @return The lengthIndicator.
     */
    com.google.protobuf.ByteString getLengthIndicator();

    /**
     * <code>.oslp.Message payload = 5;</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <code>.oslp.Message payload = 5;</code>
     * @return The payload.
     */
    org.opensmartgridplatform.oslp.Oslp.Message getPayload();
    /**
     * <code>.oslp.Message payload = 5;</code>
     */
    org.opensmartgridplatform.oslp.Oslp.MessageOrBuilder getPayloadOrBuilder();
  }
  /**
   * Protobuf type {@code oslp.OslpEnvelope}
   */
  public static final class OslpEnvelope extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:oslp.OslpEnvelope)
      OslpEnvelopeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        OslpEnvelope.class.getName());
    }
    // Use OslpEnvelope.newBuilder() to construct.
    private OslpEnvelope(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OslpEnvelope() {
      securityKey_ = com.google.protobuf.ByteString.EMPTY;
      sequenceNumber_ = com.google.protobuf.ByteString.EMPTY;
      deviceId_ = com.google.protobuf.ByteString.EMPTY;
      lengthIndicator_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Envelope.internal_static_oslp_OslpEnvelope_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Envelope.internal_static_oslp_OslpEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OslpEnvelope.class, Builder.class);
    }

    private int bitField0_;
    public static final int SECURITYKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString securityKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes SecurityKey = 1;</code>
     * @return Whether the securityKey field is set.
     */
    @Override
    public boolean hasSecurityKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>bytes SecurityKey = 1;</code>
     * @return The securityKey.
     */
    @Override
    public com.google.protobuf.ByteString getSecurityKey() {
      return securityKey_;
    }

    public static final int SEQUENCENUMBER_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sequenceNumber_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes SequenceNumber = 2;</code>
     * @return Whether the sequenceNumber field is set.
     */
    @Override
    public boolean hasSequenceNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>bytes SequenceNumber = 2;</code>
     * @return The sequenceNumber.
     */
    @Override
    public com.google.protobuf.ByteString getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString deviceId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes DeviceId = 3;</code>
     * @return Whether the deviceId field is set.
     */
    @Override
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>bytes DeviceId = 3;</code>
     * @return The deviceId.
     */
    @Override
    public com.google.protobuf.ByteString getDeviceId() {
      return deviceId_;
    }

    public static final int LENGTHINDICATOR_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString lengthIndicator_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes LengthIndicator = 4;</code>
     * @return Whether the lengthIndicator field is set.
     */
    @Override
    public boolean hasLengthIndicator() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>bytes LengthIndicator = 4;</code>
     * @return The lengthIndicator.
     */
    @Override
    public com.google.protobuf.ByteString getLengthIndicator() {
      return lengthIndicator_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 5;
    private org.opensmartgridplatform.oslp.Oslp.Message payload_;
    /**
     * <code>.oslp.Message payload = 5;</code>
     * @return Whether the payload field is set.
     */
    @Override
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.oslp.Message payload = 5;</code>
     * @return The payload.
     */
    @Override
    public org.opensmartgridplatform.oslp.Oslp.Message getPayload() {
      return payload_ == null ? org.opensmartgridplatform.oslp.Oslp.Message.getDefaultInstance() : payload_;
    }
    /**
     * <code>.oslp.Message payload = 5;</code>
     */
    @Override
    public org.opensmartgridplatform.oslp.Oslp.MessageOrBuilder getPayloadOrBuilder() {
      return payload_ == null ? org.opensmartgridplatform.oslp.Oslp.Message.getDefaultInstance() : payload_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasPayload()) {
        if (!getPayload().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, securityKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, deviceId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, lengthIndicator_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeMessage(5, getPayload());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, securityKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, deviceId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, lengthIndicator_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPayload());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OslpEnvelope)) {
        return super.equals(obj);
      }
      OslpEnvelope other = (OslpEnvelope) obj;

      if (hasSecurityKey() != other.hasSecurityKey()) return false;
      if (hasSecurityKey()) {
        if (!getSecurityKey()
            .equals(other.getSecurityKey())) return false;
      }
      if (hasSequenceNumber() != other.hasSequenceNumber()) return false;
      if (hasSequenceNumber()) {
        if (!getSequenceNumber()
            .equals(other.getSequenceNumber())) return false;
      }
      if (hasDeviceId() != other.hasDeviceId()) return false;
      if (hasDeviceId()) {
        if (!getDeviceId()
            .equals(other.getDeviceId())) return false;
      }
      if (hasLengthIndicator() != other.hasLengthIndicator()) return false;
      if (hasLengthIndicator()) {
        if (!getLengthIndicator()
            .equals(other.getLengthIndicator())) return false;
      }
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
            .equals(other.getPayload())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecurityKey()) {
        hash = (37 * hash) + SECURITYKEY_FIELD_NUMBER;
        hash = (53 * hash) + getSecurityKey().hashCode();
      }
      if (hasSequenceNumber()) {
        hash = (37 * hash) + SEQUENCENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getSequenceNumber().hashCode();
      }
      if (hasDeviceId()) {
        hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceId().hashCode();
      }
      if (hasLengthIndicator()) {
        hash = (37 * hash) + LENGTHINDICATOR_FIELD_NUMBER;
        hash = (53 * hash) + getLengthIndicator().hashCode();
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OslpEnvelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OslpEnvelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OslpEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OslpEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OslpEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OslpEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OslpEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OslpEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static OslpEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static OslpEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OslpEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OslpEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OslpEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oslp.OslpEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oslp.OslpEnvelope)
        OslpEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Envelope.internal_static_oslp_OslpEnvelope_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Envelope.internal_static_oslp_OslpEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OslpEnvelope.class, Builder.class);
      }

      // Construct using org.opensmartgridplatform.oslp.Envelope.OslpEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetPayloadFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        securityKey_ = com.google.protobuf.ByteString.EMPTY;
        sequenceNumber_ = com.google.protobuf.ByteString.EMPTY;
        deviceId_ = com.google.protobuf.ByteString.EMPTY;
        lengthIndicator_ = com.google.protobuf.ByteString.EMPTY;
        payload_ = null;
        if (payloadBuilder_ != null) {
          payloadBuilder_.dispose();
          payloadBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Envelope.internal_static_oslp_OslpEnvelope_descriptor;
      }

      @Override
      public OslpEnvelope getDefaultInstanceForType() {
        return OslpEnvelope.getDefaultInstance();
      }

      @Override
      public OslpEnvelope build() {
        OslpEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OslpEnvelope buildPartial() {
        OslpEnvelope result = new OslpEnvelope(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(OslpEnvelope result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.securityKey_ = securityKey_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sequenceNumber_ = sequenceNumber_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.deviceId_ = deviceId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lengthIndicator_ = lengthIndicator_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.payload_ = payloadBuilder_ == null
              ? payload_
              : payloadBuilder_.build();
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OslpEnvelope) {
          return mergeFrom((OslpEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OslpEnvelope other) {
        if (other == OslpEnvelope.getDefaultInstance()) return this;
        if (other.hasSecurityKey()) {
          setSecurityKey(other.getSecurityKey());
        }
        if (other.hasSequenceNumber()) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasLengthIndicator()) {
          setLengthIndicator(other.getLengthIndicator());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (hasPayload()) {
          if (!getPayload().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                securityKey_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                sequenceNumber_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                deviceId_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                lengthIndicator_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    internalGetPayloadFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString securityKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes SecurityKey = 1;</code>
       * @return Whether the securityKey field is set.
       */
      @Override
      public boolean hasSecurityKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>bytes SecurityKey = 1;</code>
       * @return The securityKey.
       */
      @Override
      public com.google.protobuf.ByteString getSecurityKey() {
        return securityKey_;
      }
      /**
       * <code>bytes SecurityKey = 1;</code>
       * @param value The securityKey to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        securityKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes SecurityKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        securityKey_ = getDefaultInstance().getSecurityKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sequenceNumber_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes SequenceNumber = 2;</code>
       * @return Whether the sequenceNumber field is set.
       */
      @Override
      public boolean hasSequenceNumber() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>bytes SequenceNumber = 2;</code>
       * @return The sequenceNumber.
       */
      @Override
      public com.google.protobuf.ByteString getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <code>bytes SequenceNumber = 2;</code>
       * @param value The sequenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceNumber(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        sequenceNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes SequenceNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceNumber_ = getDefaultInstance().getSequenceNumber();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString deviceId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes DeviceId = 3;</code>
       * @return Whether the deviceId field is set.
       */
      @Override
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>bytes DeviceId = 3;</code>
       * @return The deviceId.
       */
      @Override
      public com.google.protobuf.ByteString getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>bytes DeviceId = 3;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        deviceId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes DeviceId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString lengthIndicator_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes LengthIndicator = 4;</code>
       * @return Whether the lengthIndicator field is set.
       */
      @Override
      public boolean hasLengthIndicator() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>bytes LengthIndicator = 4;</code>
       * @return The lengthIndicator.
       */
      @Override
      public com.google.protobuf.ByteString getLengthIndicator() {
        return lengthIndicator_;
      }
      /**
       * <code>bytes LengthIndicator = 4;</code>
       * @param value The lengthIndicator to set.
       * @return This builder for chaining.
       */
      public Builder setLengthIndicator(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        lengthIndicator_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes LengthIndicator = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLengthIndicator() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lengthIndicator_ = getDefaultInstance().getLengthIndicator();
        onChanged();
        return this;
      }

      private org.opensmartgridplatform.oslp.Oslp.Message payload_;
      private com.google.protobuf.SingleFieldBuilder<
          org.opensmartgridplatform.oslp.Oslp.Message, org.opensmartgridplatform.oslp.Oslp.Message.Builder, org.opensmartgridplatform.oslp.Oslp.MessageOrBuilder> payloadBuilder_;
      /**
       * <code>.oslp.Message payload = 5;</code>
       * @return Whether the payload field is set.
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       * @return The payload.
       */
      public org.opensmartgridplatform.oslp.Oslp.Message getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? org.opensmartgridplatform.oslp.Oslp.Message.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       */
      public Builder setPayload(org.opensmartgridplatform.oslp.Oslp.Message value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
        } else {
          payloadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       */
      public Builder setPayload(
          org.opensmartgridplatform.oslp.Oslp.Message.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       */
      public Builder mergePayload(org.opensmartgridplatform.oslp.Oslp.Message value) {
        if (payloadBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            payload_ != null &&
            payload_ != org.opensmartgridplatform.oslp.Oslp.Message.getDefaultInstance()) {
            getPayloadBuilder().mergeFrom(value);
          } else {
            payload_ = value;
          }
        } else {
          payloadBuilder_.mergeFrom(value);
        }
        if (payload_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = null;
        if (payloadBuilder_ != null) {
          payloadBuilder_.dispose();
          payloadBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       */
      public org.opensmartgridplatform.oslp.Oslp.Message.Builder getPayloadBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return internalGetPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       */
      public org.opensmartgridplatform.oslp.Oslp.MessageOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
              org.opensmartgridplatform.oslp.Oslp.Message.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>.oslp.Message payload = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.opensmartgridplatform.oslp.Oslp.Message, org.opensmartgridplatform.oslp.Oslp.Message.Builder, org.opensmartgridplatform.oslp.Oslp.MessageOrBuilder> 
          internalGetPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.opensmartgridplatform.oslp.Oslp.Message, org.opensmartgridplatform.oslp.Oslp.Message.Builder, org.opensmartgridplatform.oslp.Oslp.MessageOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:oslp.OslpEnvelope)
    }

    // @@protoc_insertion_point(class_scope:oslp.OslpEnvelope)
    private static final OslpEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OslpEnvelope();
    }

    public static OslpEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OslpEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<OslpEnvelope>() {
      @Override
      public OslpEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OslpEnvelope> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OslpEnvelope> getParserForType() {
      return PARSER;
    }

    @Override
    public OslpEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oslp_OslpEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_oslp_OslpEnvelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016envelope.proto\022\004oslp\032\noslp.proto\"\206\001\n\014O" +
      "slpEnvelope\022\023\n\013SecurityKey\030\001 \001(\014\022\026\n\016Sequ" +
      "enceNumber\030\002 \001(\014\022\020\n\010DeviceId\030\003 \001(\014\022\027\n\017Le" +
      "ngthIndicator\030\004 \001(\014\022\036\n\007payload\030\005 \001(\0132\r.o" +
      "slp.MessageB \n\036org.opensmartgridplatform" +
      ".oslpb\010editionsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.opensmartgridplatform.oslp.Oslp.getDescriptor(),
        });
    internal_static_oslp_OslpEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_oslp_OslpEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_oslp_OslpEnvelope_descriptor,
        new String[] { "SecurityKey", "SequenceNumber", "DeviceId", "LengthIndicator", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    org.opensmartgridplatform.oslp.Oslp.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
