/*
 * Copyright 2015 Smart Society Services B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */
package org.opensmartgridplatform.domain.core.valueobjects;

public enum EventType {
  DIAG_EVENTS_GENERAL(0),
  DIAG_EVENTS_UNKNOWN_MESSAGE_TYPE(1),
  HARDWARE_FAILURE_RELAY(2),
  HARDWARE_FAILURE_FLASH_WRITE_ERROR(3),
  HARDWARE_FAILURE_FLASH_MEMORY_CORRUPT(4),
  HARDWARE_FAILURE_RTC_NOT_SET(5),
  LIGHT_FAILURE_DALI_COMMUNICATION(6),
  LIGHT_FAILURE_BALLAST(7),
  LIGHT_EVENTS_LIGHT_ON(8),
  LIGHT_EVENTS_LIGHT_OFF(9),
  MONITOR_EVENTS_LONG_BUFFER_FULL(10),
  FIRMWARE_EVENTS_ACTIVATING(11),
  FIRMWARE_EVENTS_DOWNLOAD_NOTFOUND(12),
  FIRMWARE_EVENTS_DOWNLOAD_FAILED(13),
  LIGHT_FAILURE_TARIFF_SWITCH_ATTEMPT(14),
  TARIFF_EVENTS_TARIFF_ON(15),
  TARIFF_EVENTS_TARIFF_OFF(16),
  MONITOR_FAILURE_P1_COMMUNICATION(17),
  COMM_EVENTS_ALTERNATIVE_CHANNEL(18),
  COMM_EVENTS_RECOVERED_CHANNEL(19),
  SECURITY_EVENTS_OUT_OF_SEQUENCE(20),
  SECURITY_EVENTS_OSLP_VERIFICATION_FAILED(21),
  SECURITY_EVENTS_INVALID_CERTIFICATE(22),
  MONITOR_SHORT_DETECTED(23),
  MONITOR_SHORT_RESOLVED(24),
  MONITOR_DOOR_OPENED(25),
  MONITOR_DOOR_CLOSED(26),
  ALARM_NOTIFICATION(27),
  SMS_NOTIFICATION(28),
  MONITOR_EVENTS_TEST_RELAY_ON(29),
  MONITOR_EVENTS_TEST_RELAY_OFF(30),
  MONITOR_EVENTS_LOSS_OF_POWER(31),
  MONITOR_EVENTS_LOCAL_MODE(32),
  MONITOR_EVENTS_REMOTE_MODE(33),
  FIRMWARE_EVENTS_CONFIGURATION_CHANGED(34),
  FIRMWARE_EVENTS_DOWNLOAD_SUCCESS(35),
  CA_FILE_EVENTS_ACTIVATING(36),
  CA_FILE_FIRMWARE_EVENTS_DOWNLOAD_NOT_FOUND(37),
  CA_FILE_EVENTS_DOWNLOAD_FAILED(38),
  CA_FILE_EVENTS_DOWNLOAD_SUCCESS(39),
  NTP_SERVER_NOT_REACH(40),
  NTP_SYNC_ALARM_OFFSET(41),
  NTP_SYNC_MAX_OFFSET(42),
  NTP_SYNC_SUCCESS(43),
  AUTHENTICATION_FAIL(44),
  LIGHT_SENSOR_REPORTS_DARK(45),
  LIGHT_SENSOR_REPORTS_LIGHT(46),
  SYSTEM_EVENT(47);

  private final int value;

  EventType(final int value) {
    this.value = value;
  }

  public int getValue() {
    return this.value;
  }
}
