// SPDX-FileCopyrightText: Copyright Contributors to the GXF project
//
// SPDX-License-Identifier: Apache-2.0

package org.opensmartgridplatform.dlms.objectconfig;

public enum DlmsObjectType {
  CLOCK,
  DEFINABLE_LOAD_PROFILE,
  POWER_QUALITY_PROFILE_1,
  POWER_QUALITY_PROFILE_2,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT_L1,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT_L2,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT_L3,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT_L1,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT_L2,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT_L3,
  INSTANTANEOUS_ACTIVE_CURRENT_TOTAL_OVER_ALL_PHASES,
  INSTANTANEOUS_CURRENT_L1,
  INSTANTANEOUS_CURRENT_L2,
  INSTANTANEOUS_CURRENT_L3,
  INSTANTANEOUS_VOLTAGE_L1,
  INSTANTANEOUS_VOLTAGE_L2,
  INSTANTANEOUS_VOLTAGE_L3,
  AVERAGE_ACTIVE_POWER_IMPORT_L1,
  AVERAGE_ACTIVE_POWER_IMPORT_L2,
  AVERAGE_ACTIVE_POWER_IMPORT_L3,
  AVERAGE_ACTIVE_POWER_EXPORT_L1,
  AVERAGE_ACTIVE_POWER_EXPORT_L2,
  AVERAGE_ACTIVE_POWER_EXPORT_L3,
  AVERAGE_REACTIVE_POWER_IMPORT_L1,
  AVERAGE_REACTIVE_POWER_IMPORT_L2,
  AVERAGE_REACTIVE_POWER_IMPORT_L3,
  AVERAGE_REACTIVE_POWER_EXPORT_L1,
  AVERAGE_REACTIVE_POWER_EXPORT_L2,
  AVERAGE_REACTIVE_POWER_EXPORT_L3,
  AVERAGE_CURRENT_L1,
  AVERAGE_CURRENT_L2,
  AVERAGE_CURRENT_L3,
  AVERAGE_VOLTAGE_L1,
  AVERAGE_VOLTAGE_L2,
  AVERAGE_VOLTAGE_L3,
  NUMBER_OF_POWER_FAILURES,
  NUMBER_OF_LONG_POWER_FAILURES,
  NUMBER_OF_VOLTAGE_SAGS_FOR_L1,
  NUMBER_OF_VOLTAGE_SAGS_FOR_L2,
  NUMBER_OF_VOLTAGE_SAGS_FOR_L3,
  NUMBER_OF_VOLTAGE_SWELLS_FOR_L1,
  NUMBER_OF_VOLTAGE_SWELLS_FOR_L2,
  NUMBER_OF_VOLTAGE_SWELLS_FOR_L3,
  CDMA_DIAGNOSTIC,
  GPRS_DIAGNOSTIC,
  LTE_DIAGNOSTIC,
  MBUS_CLIENT_SETUP,
  MBUS_DIAGNOSTIC,
  PUSH_SETUP_UDP,
  ALARM_REGISTER_1,
  ALARM_REGISTER_2,
  ALARM_REGISTER_3,
  READ_MBUS_STATUS,
  CLEAR_MBUS_STATUS;

  public String value() {
    return this.name();
  }

  public static DlmsObjectType fromValue(final String v) {
    return valueOf(v);
  }
}
