/*
 * Copyright 2022 Alliander N.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 */

package org.opensmartgridplatform.dlms.objectconfig;

public enum DlmsObjectType {
  CLOCK,
  DEFINABLE_LOAD_PROFILE,
  POWER_QUALITY_PROFILE_1,
  POWER_QUALITY_PROFILE_2,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT_L1,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT_L2,
  INSTANTANEOUS_ACTIVE_POWER_IMPORT_L3,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT_L1,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT_L2,
  INSTANTANEOUS_ACTIVE_POWER_EXPORT_L3,
  INSTANTANEOUS_CURRENT_L1,
  INSTANTANEOUS_CURRENT_L2,
  INSTANTANEOUS_CURRENT_L3,
  INSTANTANEOUS_VOLTAGE_L1,
  INSTANTANEOUS_VOLTAGE_L2,
  INSTANTANEOUS_VOLTAGE_L3,
  AVERAGE_ACTIVE_POWER_IMPORT_L1,
  AVERAGE_ACTIVE_POWER_IMPORT_L2,
  AVERAGE_ACTIVE_POWER_IMPORT_L3,
  AVERAGE_ACTIVE_POWER_EXPORT_L1,
  AVERAGE_ACTIVE_POWER_EXPORT_L2,
  AVERAGE_ACTIVE_POWER_EXPORT_L3,
  AVERAGE_REACTIVE_POWER_IMPORT_L1,
  AVERAGE_REACTIVE_POWER_IMPORT_L2,
  AVERAGE_REACTIVE_POWER_IMPORT_L3,
  AVERAGE_REACTIVE_POWER_EXPORT_L1,
  AVERAGE_REACTIVE_POWER_EXPORT_L2,
  AVERAGE_REACTIVE_POWER_EXPORT_L3,
  AVERAGE_CURRENT_L1,
  AVERAGE_CURRENT_L2,
  AVERAGE_CURRENT_L3,
  AVERAGE_VOLTAGE_L1,
  AVERAGE_VOLTAGE_L2,
  AVERAGE_VOLTAGE_L3,
  NUMBER_OF_POWER_FAILURES,
  NUMBER_OF_LONG_POWER_FAILURES,
  NUMBER_OF_VOLTAGE_SAGS_L1,
  NUMBER_OF_VOLTAGE_SAGS_L2,
  NUMBER_OF_VOLTAGE_SAGS_L3,
  NUMBER_OF_VOLTAGE_SWELLS_L1,
  NUMBER_OF_VOLTAGE_SWELLS_L2,
  NUMBER_OF_VOLTAGE_SWELLS_L3,
  CDMA_DIAGNOSTIC,
  GPRS_DIAGNOSTIC,
  MBUS_CLIENT_SETUP,
  MBUS_DIAGNOSTIC;

  public String value() {
    return this.name();
  }

  public static DlmsObjectType fromValue(final String v) {
    return valueOf(v);
  }
}
