package org.opensmartgridplatform.adapter.protocol.dlms.domain.commands.dlmsobjectconfig;

// @formatter:off
public enum DlmsObjectType {
    AMR_STATUS,
    AMR_STATUS_MBUS,
    CLOCK,
    ACTIVE_ENERGY_IMPORT,
    ACTIVE_ENERGY_IMPORT_RATE_1,
    ACTIVE_ENERGY_IMPORT_RATE_2,
    ACTIVE_ENERGY_EXPORT,
    ACTIVE_ENERGY_EXPORT_RATE_1,
    ACTIVE_ENERGY_EXPORT_RATE_2,
    DAILY_LOAD_PROFILE_COMBINED,
    INTERVAL_VALUES_E,
    MONTHLY_BILLING_VALUES_E,
    MBUS_MASTER_VALUE,
    DAILY_LOAD_PROFILE_G,
    INTERVAL_VALUES_G,
    MONTHLY_BILLING_VALUES_COMBINED,
}
