#spring.profiles.active=default_controlled_station
spring.profiles.default=light_measurement_device

management.server.port=9404
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
