-- SPDX-FileCopyrightText: 2023 Contributors to the GXF project
-- SPDX-FileCopyrightText: Contributors to the GXF project
--
-- SPDX-License-Identifier: Apache-2.0

COMMENT ON COLUMN device.device_identification IS 'Business key; identification of this device.';
COMMENT ON COLUMN device.device_type IS 'The type [SSLD, PSLD] of this device.';
COMMENT ON COLUMN device.is_activated IS 'Indicates whether or not this device is activated.';
COMMENT ON COLUMN device.container_city IS 'The city of this device.';
COMMENT ON COLUMN device.container_street IS 'The street of this device.';
COMMENT ON COLUMN device.gps_latitude IS 'The latitude of the GPS coordinates of a device.';
COMMENT ON COLUMN device.gps_longitude IS 'The longitude of the GPS coordinates of a device.';
COMMENT ON COLUMN device.container_postal_code IS 'The postal code of this device.';
COMMENT ON COLUMN device.container_number IS 'The street number of this device.';
COMMENT ON COLUMN device.protocol_info_id IS 'Primary key of a protocol info for this device.';
COMMENT ON COLUMN device.network_address IS 'The IP address of this device.';
COMMENT ON COLUMN device.container_municipality IS 'The municipality of this device.';
COMMENT ON COLUMN device.alias IS 'The alias of this device.';
COMMENT ON COLUMN device.in_maintenance IS 'Indicates whether or not this device is in maintenance.';
COMMENT ON COLUMN device.gateway_device_id IS 'Primary key of another device which is used as gateway for this device.';
COMMENT ON COLUMN device.technical_installation_date IS 'The technical installation date which is set during installation of this device.';
COMMENT ON COLUMN device.device_model IS 'Primary key of a device model for this device.';
COMMENT ON COLUMN device.device_lifecycle_status IS 'The lifecycle [NEW_IN_INVENTORY, READY_FOR_USE, REGISTERED, IN_USE, RETURNED_TO_INVENTORY, UNDER_TEST, DESTROYED] of this device.';
COMMENT ON COLUMN device_authorization.function_group IS 'The function group [OWNER, INSTALLATION, AD_HOC, MANAGEMENT, FIRMWARE, SCHEDULING, TARIFF_SCHEDULING, CONFIGURATION, MONITORING, METADATA_MANAGEMENT] for this device authorization.';
COMMENT ON COLUMN device_authorization.device IS 'Primary key of a device for this device authorization.';
COMMENT ON COLUMN device_authorization.organisation IS 'Primary key of an organisation for this device authorization.';
COMMENT ON COLUMN device_current_firmware_module_version.device_id IS 'Primary key of a device for this firmware module version.';
COMMENT ON COLUMN device_current_firmware_module_version.module_description IS 'The description of this firmware module version.';
COMMENT ON COLUMN device_current_firmware_module_version.module_version IS 'The version of this firmware module version.';
COMMENT ON COLUMN device_firmware_file.installation_date IS 'Timestamp which indicates when a firmware was installed on a device.';
COMMENT ON COLUMN device_firmware_file.installed_by IS 'The user name of the user who installed the firmware on a device.';
COMMENT ON COLUMN device_firmware_file.device_id IS 'Primary key of a device.';
COMMENT ON COLUMN device_firmware_file.firmware_file_id IS 'Primary key of a firmware file.';
COMMENT ON COLUMN device_function_mapping.function_group IS 'The function group [OWNER, INSTALLATION, AD_HOC, MANAGEMENT, FIRMWARE, SCHEDULING, TARIFF_SCHEDULING, CONFIGURATION, MONITORING, METADATA_MANAGEMENT] for this device function mapping.';
COMMENT ON COLUMN device_function_mapping.function IS 'The device function (examples are: START_SELF_TEST, STOP_SELF_TEST, SET_LIGHT, etc.) for this device function mapping. ';
COMMENT ON COLUMN device_model.manufacturer_id IS 'The primary key of this model''s manufacturer.';
COMMENT ON COLUMN device_model.model_code IS 'The model code of this device model.';
COMMENT ON COLUMN device_model.description IS 'The description of this device model.';
COMMENT ON COLUMN device_model.file_storage IS 'Indicates whether or not this device model uses the file system to store firmware files.';
COMMENT ON COLUMN device_model.metered IS 'Indicates whether or not this device model can be equipped with an electricity meter.';
COMMENT ON COLUMN device_model_firmware_file.device_model_id IS 'Primary key of a device model.';
COMMENT ON COLUMN device_model_firmware_file.firmware_file_id IS 'Primary key of a firmware file.';
COMMENT ON COLUMN device_output_setting.device_id IS 'Primary key of a device for this device output setting.';
COMMENT ON COLUMN device_output_setting.internal_id IS 'The actual relay number used to configure a relay of an SSLD.';
COMMENT ON COLUMN device_output_setting.external_id IS 'The virtual relay number used to configure a relay of an SSLD.';
COMMENT ON COLUMN device_output_setting.output_type IS 'The output type [LIGHT, TARIFF, TARIFF_REVERSED] of this device output setting.';
COMMENT ON COLUMN device_output_setting.alias IS 'The alias for this relay of this device output setting.';
COMMENT ON COLUMN device_output_setting.relay_function IS 'The relay function [BURNER, EVENING_MORNING, TARIFF, SPECIAL, NOT_CONNECTED] of this device output setting.';
COMMENT ON COLUMN domain_info.domain IS 'The domain of this domain info.';
COMMENT ON COLUMN domain_info.domain_version IS 'The domain version of this domain info.';
COMMENT ON COLUMN domain_info.incoming_domain_requests_queue IS 'The incoming requests queue for this domain info.';
COMMENT ON COLUMN domain_info.outgoing_domain_responses_queue IS 'The outgoing responses queue for this domain info.';
COMMENT ON COLUMN domain_info.outgoing_domain_requests_queue IS 'The outgoing requests queue for this domain info.';
COMMENT ON COLUMN domain_info.incoming_domain_responses_queue IS 'The incoming responses queue for this domain info.';
COMMENT ON COLUMN ean.code IS 'Business key; the numeric EAN.';
COMMENT ON COLUMN ean.description IS 'Description for this EAN.';
COMMENT ON COLUMN ean.device IS 'Primary key of a device.';
COMMENT ON COLUMN event.description IS 'Description for this event.';
COMMENT ON COLUMN event.event IS 'The event type (see EventType.java) for this event.';
COMMENT ON COLUMN event.index IS 'The rleay on which this event occurred.';
COMMENT ON COLUMN event.device IS 'Primary key of a device.';
COMMENT ON COLUMN event.date_time IS 'Timestamp which indicates when this event occurred on the device.';
COMMENT ON COLUMN firmware_file.filename IS 'The file name of this firmware file.';
COMMENT ON COLUMN firmware_file.description IS 'The description of this firmware file.';
COMMENT ON COLUMN firmware_file.push_to_new_devices IS 'Indicates whether or not this firmware file will be sent to newly installed devices.';
COMMENT ON COLUMN firmware_file.hash IS 'The hash of this firmware file.';
COMMENT ON COLUMN firmware_file.file IS 'The firmware file.';
COMMENT ON COLUMN firmware_file.identification IS 'Business key; the identification of this firmware file.';
COMMENT ON COLUMN firmware_file_firmware_module.firmware_file_id IS 'Primary key of a firmware file.';
COMMENT ON COLUMN firmware_file_firmware_module.firmware_module_id IS 'Primary key of a firmware module.';
COMMENT ON COLUMN firmware_file_firmware_module.module_version IS 'The module version of the firmware module.';
COMMENT ON COLUMN firmware_module.description IS 'The description of a firmware module.';
COMMENT ON COLUMN light_measurement_device.description IS 'The description of this light measurement device.';
COMMENT ON COLUMN light_measurement_device.code IS 'The 7 character code of this light measurement device.';
COMMENT ON COLUMN light_measurement_device.color IS 'Hex color for this light measurement device.';
COMMENT ON COLUMN light_measurement_device.digital_input IS 'The number of the digital input pin connected to a light sensor of this light measurement device.';
COMMENT ON COLUMN light_measurement_device.last_communication_time IS 'Timestamp which indicates when the last event was received of this light measurement device.';
COMMENT ON COLUMN manufacturer.code IS 'The code of this manufacturer.';
COMMENT ON COLUMN manufacturer.name IS 'The name of this manufacturer.';
COMMENT ON COLUMN manufacturer.use_prefix IS 'Indicates whether or not devices of this manufacturer use a prefix for the device identifications.';
COMMENT ON COLUMN offloading_data.table_name IS 'The name of the table which was offloaded.';
COMMENT ON COLUMN offloading_data.end_last_date_block IS 'The timestamp which indicates when a table was offloaded for the last time.';
COMMENT ON COLUMN organisation.function_group IS 'The platform function group [ADMIN, USER] of this organisation.';
COMMENT ON COLUMN organisation.name IS 'The name of this organisation.';
COMMENT ON COLUMN organisation.organisation_identification IS 'Business key; the identification of this organisation.';
COMMENT ON COLUMN organisation.enabled IS 'Indicates whether or not this organisation is enabled.';
COMMENT ON COLUMN organisation.domains IS 'Comma separated list of platform domains [COMMON, PUBLIC_LIGHTING, TARIFF_SWITCHING] this organisation is allowed to access';
COMMENT ON COLUMN organisation.prefix IS 'The 3 character prefix of this organisation.';
COMMENT ON COLUMN protocol_info.protocol IS 'The name of the protocol of this protocol info.';
COMMENT ON COLUMN protocol_info.protocol_version IS 'The version of the protocol of this protocol info.';
COMMENT ON COLUMN protocol_info.outgoing_protocol_requests_queue IS 'The outgoing requests queue for this protocol info.';
COMMENT ON COLUMN protocol_info.incoming_protocol_responses_queue IS 'The incoming responses queue for this protocol info.';
COMMENT ON COLUMN protocol_info.incoming_protocol_requests_queue IS 'The incoming requests queue for this protocol info.';
COMMENT ON COLUMN protocol_info.outgoing_protocol_responses_queue IS 'The outgoing responses queue for this protocol info.';
COMMENT ON COLUMN relay_status.index IS 'The virtual relay number of this relay status.';
COMMENT ON COLUMN relay_status.last_known_state IS 'The state of the relay as derived from latest events of an SSLD.';
COMMENT ON COLUMN relay_status.last_know_switching_time IS 'The timestamp of the last switch event of an SSLD.';
COMMENT ON COLUMN relay_status.device_id IS 'Primary key of a device.';
--COMMENT ON COLUMN rtu_device.last_communication_time IS '';
COMMENT ON COLUMN scheduled_task.domain IS 'The domain of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.domain_version IS 'The domain version of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.correlation_uid IS 'The correlation UID of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.organisation_identification IS 'The organisation identification of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.device_identification IS 'The device identification of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.message_type IS 'The message type of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.message_data IS 'The serialized object of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.scheduled_time IS 'The time when the message should be sent by this scheduled task.';
COMMENT ON COLUMN scheduled_task.error_log IS 'The error message when the message was sent by this scheduled task.';
COMMENT ON COLUMN scheduled_task.status IS 'The status [NEW, PENDING, COMPLETE, FAILED, RETRY] of this scheduled task.';
COMMENT ON COLUMN scheduled_task.messagepriority IS 'The message priority of the message of this scheduled task.';
COMMENT ON COLUMN scheduled_task.retry IS 'The retry count of the message of this scheduled task.';
COMMENT ON COLUMN schema_version.installed_rank IS 'Installed rank indicates the order of applied migrations. Used by Flyway.';
COMMENT ON COLUMN schema_version.version IS 'Version indicates the numbered prefix of migration files. Used by Flyway.';
COMMENT ON COLUMN schema_version.description IS 'Description indicates the name of migration files. Used by Flyway.';
COMMENT ON COLUMN schema_version.type IS 'Type can be SQL in case of SQL migration files or JDBC in case of migrating programmatically using Java. Used by Flyway.';
COMMENT ON COLUMN schema_version.script IS 'Full name of the migration script; version and description are derived from the full name. Used by Flyway.';
COMMENT ON COLUMN schema_version.checksum IS 'Hash of the content of a migration script. Used by Flyway.';
COMMENT ON COLUMN schema_version.installed_by IS 'User name of the database user who has run the migration script. Used by Flyway.';
COMMENT ON COLUMN schema_version.installed_on IS 'Timestamp indicating when the migration has been applied. Used by Flyway.';
COMMENT ON COLUMN schema_version.execution_time IS 'Duration of the migration in milliseconds. Used by Flyway.';
COMMENT ON COLUMN schema_version.success IS 'State indicating whether or not the migration was successfully applied. Used by Flyway.';
--COMMENT ON COLUMN smart_meter.supplier IS '';
--COMMENT ON COLUMN smart_meter.channel IS '';
--COMMENT ON COLUMN smart_meter.mbus_identification_number IS '';
--COMMENT ON COLUMN smart_meter.mbus_manufacturer_identification IS '';
--COMMENT ON COLUMN smart_meter.mbus_version IS '';
--COMMENT ON COLUMN smart_meter.mbus_device_type_identification IS '';
--COMMENT ON COLUMN smart_meter.mbus_primary_address IS '';
COMMENT ON COLUMN ssld.has_public_key IS 'Indicates whether or not this SSLD has a public key set.';
COMMENT ON COLUMN ssld.has_schedule IS 'Indicates whether or not this SSLD has a light schedule set.';
COMMENT ON COLUMN ssld.light_measurement_device_id IS 'Primary key of a light measurement device which has been coupled with this SSLD.';
--COMMENT ON COLUMN task.task_identification IS '';
--COMMENT ON COLUMN task.task_status IS '';
--COMMENT ON COLUMN task.start_time IS '';
--COMMENT ON COLUMN task.end_time IS '';