# Creates a new release branch based on the development branch and increases the minor version in the pom files in the development branch
name: create-release-branch
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The release version to create (in «major».«minor».«patch» format)."
        required: true
        type: string
      dry_run:
        description: "Flag indicating whether it is a dry-run or not. When set to true (the default) changes are not persisted."
        required: false
        type: boolean
        default: true

env:
  ENV_FILE: .github/workflows/.env
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

jobs:
  create-release-branch:
    name: Create a new release branch
    runs-on: ubuntu-latest
    steps:
#      - name: Verify release version
#        run: bash scripts/common/verify-release-version.sh "${{ github.event.inputs.release_version }}"
#
#      - name: Setup SSH
#        if: success()
#        uses: webfactory/ssh-agent@v0.9.1
#        with:
#          ssh-private-key: |
#            ${{secrets.REPOS_PRIVATE_SSH_KEY}}

      # Checkout current repository for env file
      - name: Checkout
        if: success()
        uses: actions/checkout@v6.0.2
        # TODO - Replace feature branch ref by development branch
        with:
          ref: feature/FDP-3711-separate-releases

      - name: Verify release version
        run: bash ./.github/workflows/scripts/common/verify-release-version.sh "${{ github.event.inputs.release_version }}" "^[0-9]+[.][0-9]+[.]0$"

      - name: Setup git identity
        if: success()
        run: bash ./.github/workflows/scripts/common/setup-git-identity.sh $ENV_FILE
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout repositories
        if: success()
        id: checkout
        run: bash ./.github/workflows/scripts/common/checkout-repositories.sh $ENV_FILE
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: Verify repositories
        if: success()
        run: bash ./.github/workflows/scripts/release/verify-repositories.sh $ENV_FILE "${{ steps.checkout.outputs.repo_dir }}" "${{ github.event.inputs.release_version }}"

      - name: Update minor release version
        id: minor_version
        if: success()
        run: bash ./.github/workflows/scripts/release/update-minor-version.sh "${{ github.event.inputs.release_version }}"

      - name: Create release branches
        if: success()
        run: bash ./.github/workflows/scripts/release/create-release-branches.sh $ENV_FILE "${{ steps.checkout.outputs.repo_dir }}" "${{ github.event.inputs.release_version }}"

      - name: Increment pom version
        if: success()
        run: bash ./.github/workflows/scripts/release/increment-pom-version.sh $ENV_FILE "${{ steps.checkout.outputs.repo_dir }}"  "${{ github.event.inputs.release_version }}" "${{ steps.minor_version.outputs.new }}"

      - name: Push release branches
        if: false
        run: bash scripts/common/push-release-branches.sh $ENV_FILE "${{ steps.checkout.outputs.repo_dir }}" "${{ github.event.inputs.release_version }}" "${{ github.event.inputs.dry_run }}"
