# Creates a new patch release branch based on the previous release branch
# and increments the patch version in the pom files in the new patch release branch

name: create-patch-release-branch

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The release version for which to create a new patch release"
        required: true
        type: string
      dry_run:
        description: "Flag indicating whether it is a dry-run or not. When set to true (the default) changes are not persisted."
        required: false
        type: boolean
        default: true

env:
  ENV_FILE: .github/workflows/.env

jobs:
  create-patch-release-branch:
    name: "Create a new patch release branch"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current repo for env file and scripts"
        if: success()
        uses: actions/checkout@v6.0.2

      - name: "Verify release version"
        if: success()
        run: |
          bash ./.github/workflows/scripts/common/verify-release-version.sh \
            "${{ github.event.inputs.release_version }}" \
            "^[0-9]+[.][0-9]+[.][0-9]+$"

      - name: "Generate GitHub App token"
        id: app-token
        uses: actions/create-github-app-token@v3.0.0
        with:
          app-id: ${{ secrets.OSGP_CI_APP_ID }}
          private-key: ${{ secrets.OSGP_CI_APP_PRIVATE_KEY }}
          owner: OSGP

      - name: "Configure git"
        if: success()
        run: |
          bash ./.github/workflows/scripts/common/configure-git.sh \
            $ENV_FILE
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}

      - name: "Checkout repositories"
        id: checkout
        if: success()
        run: |
          bash ./.github/workflows/scripts/common/checkout-repositories.sh \
            $ENV_FILE

      - name: "Update patch release version"
        id: patch_version
        if: success()
        run: |
          bash ./.github/workflows/scripts/patch-release/update-patch-version.sh \
            "${{ github.event.inputs.release_version }}"

      - name: "Verify repositories"
        if: success()
        run: |
          bash ./.github/workflows/scripts/patch-release/verify-repositories.sh \
            $ENV_FILE \
            "${{ steps.checkout.outputs.repo_dir }}" \
            "${{ github.event.inputs.release_version }}" \
            "${{ steps.patch_version.outputs.new }}"

      - name: "Create Release Branches"
        if: success()
        run: |
          bash ./.github/workflows/scripts/patch-release/create-release-branches.sh \
            $ENV_FILE \
            "${{ steps.checkout.outputs.repo_dir }}" \
            "${{ github.event.inputs.release_version }}" \
            "${{ steps.patch_version.outputs.new }}"

      - name: "Increment pom version"
        if: success()
        run: |
          bash ./.github/workflows/scripts/patch-release/increment-pom-version.sh \
            $ENV_FILE \
            "${{ steps.checkout.outputs.repo_dir }}" \
            "${{ github.event.inputs.release_version }}" \
            "${{ steps.patch_version.outputs.new }}"

      - name: "Push changes"
        if: success()
        run: |
          bash ./.github/workflows/scripts/patch-release/push-changes.sh \
            $ENV_FILE \
            "${{ steps.checkout.outputs.repo_dir }}" \
            "${{ steps.patch_version.outputs.new }}" \
            "${{ github.event.inputs.dry_run }}"
