# Creates a new patch release branch based on the previous release branch and increments the patch version in the poom files in the new patch release branch
name: create-patch-release-branch
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The release version for which to create a new patch release"
        required: true
        type: string
      dry_run:
        description: "Flag indicating whether it is a dry-run or not. When set to true (the default) changes are not persisted."
        required: false
        type: boolean
        default: true

env:
  ENV_FILE: .github/workflows/.env
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

jobs:
  create-patch-release-branch:
    name: Create a new patch release branch
    runs-on: ubuntu-latest
    steps:
#      - name: Verify release version
#        run: bash scripts/common/verify-release-version.sh "${{ github.event.inputs.release_version }}"
#
#      - name: Setup SSH
#        if: success()
#        uses: webfactory/ssh-agent@v0.9.1
#        with:
#          ssh-private-key: |
#            ${{secrets.REPOS_PRIVATE_SSH_KEY}}

      # Checkout current repository for env file
      - name: Checkout
        uses: actions/checkout@v6.0.2
        # TODO - Replace feature branch ref by development branch
        with:
          ref: feature/FDP-3711-separate-releases

      - name: Verify release version
        run: bash ./.github/workflows/scripts/common/verify-release-version.sh "${{ github.event.inputs.release_version }}" "^[0-9]+[.][0-9]+[.][0-9]+$"
      - name: Setup git identity
        if: success()
        run: bash ./.github/workflows/scripts/common/setup-git-identity.sh $ENV_FILE

      - name: Checkout repositories
        id: checkout
        if: success()
        run: bash ./.github/workflows/scripts/common/checkout-repositories.sh $ENV_FILE

      - name: Update patch release version
        id: patch_version
        if: success()
        run: bash ./.github/workflows/scripts/patch-release/update-patch-version.sh "${{ github.event.inputs.release_version }}"

      - name: Verify repositories
        if: success()
        run: bash ./.github/workflows/scripts/patch-release/verify-repositories.sh $ENV_FILE "${{ steps.checkout.outputs.repo_dir }}" "${{ github.event.inputs.release_version }}" "${{ steps.patch_version.outputs.new }}"

      - name: Create Release Branches
        if: success()
        run: bash ./.github/workflows/scripts/patch-release/create-release-branches.sh $ENV_FILE "${{ steps.checkout.outputs.repo_dir }}" "${{ github.event.inputs.release_version }}" "${{ steps.patch_version.outputs.new }}"

      - name: Increment pom version
        if: success()
        run: bash ./.github/workflows/scripts/patch-release/increment-pom-version.sh $ENV_FILE "${{ steps.checkout.outputs.repo_dir }}" "${{ github.event.inputs.release_version }}" "${{ steps.patch_version.outputs.new }}"

    # Push release branches
      - name: Push Release Branches
        if: false
        run: bash ./.github/workflows/scripts/common/push-release-branches.sh $ENV_FILE ${{ steps.checkout.outputs.repo_dir }}" "${{ steps.patch_version.outputs.new }}"



