name: Maven Dependency Tree Dependency Submission
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-detection-and-submission:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
