name: Testing kubernetes cucumber test cluster
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  docker:
    name: Building docker images
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        include:
          - image: ghcr.io/osgp/osgp-core
            context: ./osgp/platform/osgp-core/
          - image: ghcr.io/osgp/osgp-logging
            context: ./osgp/platform/osgp-logging/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Maven project version
#        if: ${{ contains(github.ref, 'release') || contains(github.ref, 'development') }}
        run: echo "maven_version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        id: project
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=schedule
            type=semver,pattern={{version}},value=${{ steps.project.outputs.maven_version }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

  build:
    name: Testing kubernetes cucumber test cluster
    runs-on: ubuntu-latest
    needs: docker
    permissions:
      checks: write
    steps:
      - run: echo "DOCKER_TAG=$(echo ${{ needs.docker.outputs.tags }} | cut -d' ' -f1 | cut -d':' -f2)" >> $GITHUB_ENV
      - run: echo $DOCKER_TAG
      - name: Checkout gxf-gitops
        uses: actions/checkout@v4
        with:
          repository: 'OSGP/gxf-gitops'
          #          TODO remove when gxf-gitops is fully operational
          ref: 'feature/FDP-2849-initial-setup-gitops'
      - name: Setup k3d cluster
        run: bash setup.sh
      - name: Create gxf platform
        run: ./charts/gxf-platform/template-apply.sh $DOCKER_TAG
      - name: Create and run gxf cucumber tests
        run: ./charts/gxf-cucumber-tests/template-apply.sh $DOCKER_TAG
      - name: Wait for jobs to finish
        run: kubectl wait --for=condition=complete --all jobs --timeout=30m
      - name: Run maven cucumber reporting
        run: mvn -f charts/gxf-cucumber-tests/pom.xml verify || find charts/gxf-cucumber-tests
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "/tmp/k3dvolume/**/*.json"