name: Testing kubernetes cucumber test cluster
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  build:
    name: Testing kubernetes cucumber test cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gxf-gitops
        uses: actions/checkout@v4
        with:
          repository: 'OSGP/gxf-gitops'
          #          TODO remove when gxf-gitops is fully operational
          ref: 'feature/FDP-2849-initial-setup-gitops'
      - name: Setup k3d cluster
        run: bash setup.sh
      - name: Create gxf platform
        run: ./charts/gxf-platform/template-apply.sh
      - name: Create and run gxf cucumber tests
        run: ./charts/gxf-cucumber-tests/template-apply.sh
      - name: Wait for jobs to finish
        #        TODO wait for more than one job
        run: kubectl wait --for=condition=complete job/osgp-cucumber-tests-platform-common
      - name: Run maven cucumber reporting
        run: mvn -f charts/gxf-cucumber-tests/pom.xml verify
      - name: Show reporting
        run: find target
#        TODO publish cucumber reports to PR/action