@startuml
title Happy flow CDMA throttling
queue queue as "jms.dlms.requests.queue"
note over queue
Queue with requests for DLMS devices
coming in from OSGP Core.
end note
control DeviceRequestMessageListener <<MessageProcessor>>
note over DeviceRequestMessageListener
Abstract base class for device request
message processors,
extends DlmsConnectionMessageProcessor.
end note
control DeviceRequestMessageProcessor
control DomainHelperService
'control SessionProviderKpn
'control JasperWirelessTerminalClient
'control JasperWirelessSmsClient
control DlmsConnectionMessageProcessor
control ThrottlingClient
control DlmsConnectionHelper

queue -> DeviceRequestMessageListener : onMessage //message//
DeviceRequestMessageListener -> DeviceRequestMessageProcessor : processMessage //message//
note over DeviceRequestMessageProcessor
The flow depicted is the one for a request that
leads to a connection with an existing device.
end note
DeviceRequestMessageProcessor -> DomainHelperService : findDlmsDevice //messageMetadata//
DeviceRequestMessageProcessor -> DlmsConnectionMessageProcessor : createConnectionForDevice //device//, //messageMetadata//
DlmsConnectionMessageProcessor -> ThrottlingClient : requestPermit //bts//, //cell//
DlmsConnectionMessageProcessor <-- ThrottlingClient : //permit//
note over DlmsConnectionMessageProcessor
Creates a DLMS message listener that helps with keeping the
invocation counter up to date and/or provides detailed
logging of DLMS messages between client and server.
end note
DlmsConnectionMessageProcessor -> DlmsConnectionHelper : createConnectionForDevice //messageMetadata//, //device//, //dlmsMessageListener//
opt if an exception occurred creating the device connection in the DlmsConnectionHelper
DlmsConnectionMessageProcessor -> ThrottlingClient : releasePermit //permit//
end
DeviceRequestMessageProcessor -> DeviceRequestMessageProcessor : getResponse //connectionManager//, //device//, //message.object//, //messageMetadata//
note over DeviceRequestMessageProcessor
Operates on the device connection, and sends a response (regular or exceptional)
to OSGP Core.
end note
DeviceRequestMessageProcessor -> DlmsConnectionMessageProcessor : doConnectionPostProcessing
DlmsConnectionMessageProcessor -> ThrottlingClient : releasePermit //permit//
@enduml
